/*주석*/

-- 사용자 계정 생성
CREATE USER C##KH IDENTIFIED BY 1234;

GRANT CREATE TABLE, CREATE VIEW, RESOURCE, CONNECT TO C##KH;

--ORA-01950 발생 시,
ALTER USER C##KH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


CREATE USER C##WORKBOOK IDENTIFIED BY 1234;
GRANT CREATE TABLE, RESOURCE, CONNECT TO C##WORKBOOK;
ALTER USER C##WORKBOOK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


CREATE USER C##LHJ IDENTIFIED BY 1234;
GRANT CREATE TABLE, RESOURCE, CONNECT TO C##LHJ;
ALTER USER C##LHJ DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

DROP USER C##LHJ;

-- 계정 찾기
SELECT * FROM DBA_USERS;