

--------------------------------------------------
-- 시퀀스 삭제
--------------------------------------------------
DROP SEQUENCE SEQ_MAIN_CONTRACT ;
DROP SEQUENCE SEQ_PAYMENT ;
DROP SEQUENCE SEQ_PLAN ;
DROP SEQUENCE SEQ_DATA_SPEED ;
DROP SEQUENCE SEQ_ADD_SERVICE ;
DROP SEQUENCE SEQ_EMPLOYEE;
DROP SEQUENCE SEQ_COUNSEL;
DROP SEQUENCE SEQ_JOB;
DROP SEQUENCE SEQ_AGENCY;
DROP SEQUENCE SEQ_QA;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_QA_FILE;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_NOTICE_FILE;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_BILLING;
DROP SEQUENCE SEQ_SERVICE_CONTRACT;
DROP SEQUENCE SEQ_SERVICE_DELETE_CONFIRM;
DROP SEQUENCE SEQ_SERVICE_INSERT_CONFIRM;
DROP SEQUENCE SEQ_PLAN_CONTRACT;
DROP SEQUENCE SEQ_FIXED_INFO;
DROP SEQUENCE SEQ_ACCOUNT;
DROP SEQUENCE SEQ_PLAN_UPDATE_CONFIRM;
DROP SEQUENCE SEQ_PLAN_DELETE_CONFIRM;
DROP SEQUENCE SEQ_PLAN_INSERT_CONFIRM;
DROP SEQUENCE SEQ_MEMBER;
--------------------------------------------------
-- 테이블 삭제
--------------------------------------------------
DROP TABLE MAIN_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE PLAN CASCADE CONSTRAINTS;
DROP TABLE DATA_SPEED CASCADE CONSTRAINTS;
DROP TABLE ADD_SERVICE CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE COUNSEL CASCADE CONSTRAINTS;
DROP TABLE JOB CASCADE CONSTRAINTS;
DROP TABLE AGENCY CASCADE CONSTRAINTS;
DROP TABLE QA CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE QA_FILE CASCADE CONSTRAINTS;
DROP TABLE FAQ  CASCADE CONSTRAINTS;
DROP TABLE NOTICE_FILE CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE BILLING CASCADE CONSTRAINTS;
DROP TABLE SERVICE_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE SERVICE_DELETE_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE SERVICE_INSERT_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE PLAN_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE FIXED_INFO CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE PLAN_UPDATE_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE PLAN_DELETE_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE PLAN_INSERT_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;

--------------------------------------------------
-- 시퀀스 생성
--------------------------------------------------
CREATE SEQUENCE SEQ_MAIN_CONTRACT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAYMENT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DATA_SPEED NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADD_SERVICE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COUNSEL NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_JOB NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AGENCY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QA NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QA_FILE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FAQ NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE_FILE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPLY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BILLING NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_CONTRACT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_DELETE_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_INSERT_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_CONTRACT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FIXED_INFO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACCOUNT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_UPDATE_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_DELETE_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_INSERT_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;

--------------------------------------------------
-- 테이블 생성
--------------------------------------------------
CREATE TABLE MAIN_CONTRACT (
	NO	                          NUMBER	      DEFAULT SEQ_MAIN_CONTRACT.NEXTVAL CONSTRAINT MAIN_CONTRACT_PK PRIMARY KEY
	, TERM                        VARCHAR2(10)    DEFAULT '12'
    , DISCOUNT_RATE               NUMBER          DEFAULT 25
    , PENALTY                     NUMBER          DEFAULT 0
);

CREATE TABLE DATA_SPEED (
	NO	            NUMBER	            DEFAULT SEQ_DATA_SPEED.NEXTVAL CONSTRAINT DATA_SPEED_PK PRIMARY KEY
	 ,SPEED	        VARCHAR2(100)	    CONSTRAINT DATA_SPEED_SPEED_NN NOT NULL
	 ,DONE_SPEED	VARCHAR2(100)	    CONSTRAINT DATA_SPEED_DONE_NN NOT NULL
);

CREATE TABLE PLAN (
	NO	                NUMBER		        DEFAULT SEQ_PLAN.NEXTVAL CONSTRAINT PLAN_PK PRIMARY KEY
	 ,NAME	            VARCHAR2(100)	    CONSTRAINT PLAN_NAME_NN NOT NULL CONSTRAINT PLAN_UQ UNIQUE	
	 ,PRICE	            NUMBER	            CONSTRAINT PLAN_PRICE_NN NOT NULL 
	 ,DATA_TOTAL	    VARCHAR2(100)         CONSTRAINT PLAN_DATA_NN NOT NULL
	 ,VOICE_TOTAL	    VARCHAR2(100)	            CONSTRAINT PLAN_VOICE_NN NOT NULL
	 ,SMS_TOTAL	        VARCHAR2(100)	            CONSTRAINT PLAN_SMS_NN NOT NULL
	 ,SELL_YN	        CHAR(1)	            DEFAULT 'Y'	CONSTRAINT PLAN_YN_CK CHECK( SELL_YN IN ('Y','N'))
	 ,DATA_NO	        NUMBER	            CONSTRAINT PLAN_DATA_NO_NN NOT NULL 
     ,DATA_SHARE        VARCHAR2(100)       CONSTRAINT PLAN_DATA_SHARE_NN NOT NULL
     ,CATEGORY          VARCHAR2(100)       
     ,DESCRIPTION       VARCHAR2(4000) 
);




CREATE TABLE PAYMENT (
	NO	            NUMBER	            DEFAULT SEQ_PAYMENT.NEXTVAL CONSTRAINT PAYMENT_PK PRIMARY KEY
	, NAME	        VARCHAR2(100)	    CONSTRAINT PAYMENT_NAME_NN NOT NULL CONSTRAINT PAYMENT_NAME_UQ UNIQUE 
);

CREATE TABLE ADD_SERVICE(
    NO              NUMBER              DEFAULT SEQ_ADD_SERVICE.NEXTVAL CONSTRAINT ADD_SERVICE_PK PRIMARY KEY  
    , SERVICE       VARCHAR2(300)       CONSTRAINT ADD_SERVICE_SERVICE_NN NOT NULL
    , CONTENT       VARCHAR2(1000)      CONSTRAINT ADD_SERVICE_CONTENT_NN NOT NULL
    , PRICE         NUMBER              DEFAULT 10000
    , SELL_YN       CHAR(1)             DEFAULT 'Y'	CONSTRAINT ADD_SERVICE_YN_CK CHECK( SELL_YN IN ('Y','N'))
    , CREATED_AT    TIMESTAMP           DEFAULT SYSDATE
    , CATEGORY      VARCHAR2(100)       CONSTRAINT ADD_SERVICE_CK CHECK( CATEGORY IN ('DATA','OTT','SECURITY','INSURANCE','ROAMING'))
    
);
CREATE TABLE EMPLOYEE(
    NO                      NUMBER          DEFAULT SEQ_EMPLOYEE.NEXTVAL CONSTRAINT EMPLOYEE_PK PRIMARY KEY
    ,AGENCY_NO              NUMBER          CONSTRAINT EMPLOYEE_AGENCY_NO_NN NOT NULL
    ,ID                     VARCHAR2(100)   CONSTRAINT EMPLOYEE_ID_NN NOT NULL CONSTRAINT EMPLOYEE_ID_UQ UNIQUE
    ,PW                     VARCHAR2(100)   CONSTRAINT EMPLOYEE_PW_NN NOT NULL
    ,NAME                   VARCHAR2(100)   CONSTRAINT EMPLOYEE_NAME_NN NOT NULL
    ,PHONE                  CHAR(11)        CONSTRAINT EMPLOYEE_PHONE_NN NOT NULL
    ,ADDRESS                VARCHAR2(100)   CONSTRAINT EMPLOYEE_ADDRESS_NN NOT NULL
    ,ADDRESS2                VARCHAR2(100)   CONSTRAINT EMPLOYEE_ADDRESS2_NN NOT NULL
    ,EMAIL                  VARCHAR2(100)   CONSTRAINT EMPLOYEE_EMAIL_NN NOT NULL
    ,JOB_NO                 NUMBER          DEFAULT 1 CONSTRAINT EMPLOYEE_JOB_NO_NN NOT NULL
    ,RESIDENT               CHAR(13)        CONSTRAINT EMPLOYEE_RESIDENT_NN NOT NULL
    ,SALARY                 NUMBER          DEFAULT 2000000 CONSTRAINT EMPLOYEE_SALARY_NN NOT NULL
    ,CREATED_AT             TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP       
    ,QUIT_YN                CHAR(1)         DEFAULT 'N' CONSTRAINT EMPLOYEE_QUIT_YN_CK CHECK( QUIT_YN IN ('Y','N') )
    ,PROFILE_CHANGE_NAME    VARCHAR2(1000)
    ,PROFILE_ORIGIN_NAME    VARCHAR2(1000)
);

CREATE TABLE COUNSEL(
    NO              NUMBER          DEFAULT SEQ_COUNSEL.NEXTVAL CONSTRAINT COUNSEL_PK PRIMARY KEY
    ,MEMBER_NO      NUMBER          CONSTRAINT COUNSEL_MEMBER_NO_NN NOT NULL
    ,COUNSEL_DATE   TIMESTAMP       DEFAULT SYSDATE
    ,CONTENT        VARCHAR2(4000)  CONSTRAINT COUNSEL_CONTENT_NN NOT NULL
    ,WRITER_NO      NUMBER          CONSTRAINT COUNSEL_WRITER_NO_NN NOT NULL
    
);

CREATE TABLE JOB(
    NO              NUMBER          DEFAULT SEQ_JOB.NEXTVAL CONSTRAINT JOB_PK PRIMARY KEY
    ,JOB_NAME       VARCHAR2(100)   CONSTRAINT JOB_JOB_NAME_NN NOT NULL CONSTRAINT JOB_JOB_NAME_UQ UNIQUE
);

CREATE TABLE AGENCY(
    NO                      NUMBER          DEFAULT SEQ_AGENCY.NEXTVAL CONSTRAINT AGENCY_PK PRIMARY KEY
    ,MANAGER_NO             NUMBER          
    ,NAME                   VARCHAR2(100)   CONSTRAINT AGENCY_NAME_NN NOT NULL
    ,PHONE                  CHAR(11)        CONSTRAINT AGENCY_PHONE_NN NOT NULL
    ,ADDRESS                VARCHAR2(100)   CONSTRAINT AGENCY_ADDRESS_NN NOT NULL
    ,CREATED_AT             TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP       
    ,QUIT_YN                CHAR(1)         DEFAULT 'N' CONSTRAINT AGENCY_QUIT_YN_CK CHECK( QUIT_YN IN ('Y','N') )
);

CREATE TABLE QA(
    NO                      NUMBER            DEFAULT SEQ_QA.NEXTVAL CONSTRAINT QA_PK PRIMARY KEY   
    ,TITLE                  VARCHAR2(100)     CONSTRAINT QA_TITLE_NN NOT NULL 
    ,CONTENT                VARCHAR2(4000)    CONSTRAINT QA_CONTENT_NN NOT NULL 
    ,CATEGORY               VARCHAR2(100)     CONSTRAINT QA_CATEGORY_NN NOT NULL
    ,CREATED_AT             TIMESTAMP         DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP         
    ,WRITER_NO              NUMBER            CONSTRAINT QA_WRITER_NO_NN NOT NULL  
    ,DEL_YN                 CHAR(1)           DEFAULT 'N' CONSTRAINT QA_DEL_YN_CK CHECK( DEL_YN IN ('Y','N') )
    );

CREATE TABLE NOTICE(
    NO                      NUMBER          DEFAULT SEQ_NOTICE.NEXTVAL CONSTRAINT NOTICE_PK PRIMARY KEY   
    ,WRITER_NO              NUMBER          CONSTRAINT NOTICE_WRITER_NO_NN NOT NULL 
    ,TITLE                  VARCHAR2(100)   CONSTRAINT NOTICE_TITLE_NN NOT NULL
    ,CONTENT                VARCHAR2(4000)  CONSTRAINT NOTICE_CONTENT_NN NOT NULL
    ,HIT                    NUMBER          DEFAULT 0
    ,CREATED_AT             TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP       
    ,DEL_YN                 CHAR(1)         DEFAULT 'N' CONSTRAINT NOTICE_DEL_YN_CK CHECK( DEL_YN IN ('Y','N') )
);

CREATE TABLE FAQ(
    NO                NUMBER          DEFAULT SEQ_FAQ.NEXTVAL CONSTRAINT FAQ_PK PRIMARY KEY
    ,QUESTION         VARCHAR2(100)   CONSTRAINT FAQ_QUESTION_NN NOT NULL
    ,ANSWER           VARCHAR2(4000)  CONSTRAINT FAQ_ANSWER_NN NOT NULL
    ,CATEGORY         VARCHAR2(100)   CONSTRAINT FAQ_CATEGORY_NN NOT NULL CONSTRAINT FAQ_CATEGORY_CK CHECK( CATEGORY IN ('서비스문의','요금제문의', '약정문의' , '부가서비스문의' , '대리점문의')  )
    ,WRITER_NO        NUMBER          CONSTRAINT FAQ_WRITER_NO_NN NOT NULL
    ,CREATED_AT       TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT       TIMESTAMP 
    ,DEL_YN           CHAR(1)         DEFAULT 'N' CONSTRAINT FAQ_DEL_YN_CK CHECK( DEL_YN IN ('Y','N') )
   
);
---------------------------------------------------------
CREATE TABLE QA_FILE(
    NO               NUMBER            DEFAULT SEQ_QA_FILE.NEXTVAL CONSTRAINT QA_FILE_PK PRIMARY KEY
  ,NAME              VARCHAR2(1000)    CONSTRAINT QA_FILE_NAME_NN NOT NULL 
  ,URL               VARCHAR2(4000)    CONSTRAINT QA_FILE_URL_NN NOT NULL
  ,ORIGIN_NAME       VARCHAR2(100)     CONSTRAINT QA_FILE_ORIGIN_NAME_NN NOT NULL 
  ,QA_NO             NUMBER            CONSTRAINT QA_FILE_QA_NO_NN NOT NULL
  );
  
  CREATE TABLE NOTICE_FILE(
    NO              NUMBER            DEFAULT SEQ_NOTICE_FILE.NEXTVAL CONSTRAINT NOTICE_FILE_PK PRIMARY KEY
    ,NAME           VARCHAR2(1000)    CONSTRAINT NOTICE_FILE_NAME_NN NOT NULL
    ,URL            VARCHAR2(4000)    CONSTRAINT NOTICE_FILE_URL_NN NOT NULL
    ,ORIGIN_NAME    VARCHAR2(100)     CONSTRAINT NOTICE_FILE_ORIGIN_NAME_NN NOT NULL  
    ,NOTICE_NO      NUMBER            CONSTRAINT NOTICE_FILE_NOTICE_NO_NN NOT NULL
);

CREATE TABLE REPLY(
    NO            NUMBER            DEFAULT SEQ_REPLY.NEXTVAL CONSTRAINT REPLY_PK PRIMARY KEY
    ,CONTENT      VARCHAR2(1000)    CONSTRAINT REPLY_CONTENT_NN NOT NULL   
    ,CREATED_AT   TIMESTAMP         DEFAULT SYSDATE
    ,EMPLOYEE_NO  NUMBER            CONSTRAINT REPLY_EMPLOYEE_NO_NN NOT NULL
    ,QA_NO        NUMBER            CONSTRAINT REPLY_QA_NO_NN NOT NULL
);

CREATE TABLE BILLING (
	NO	                NUMBER	        DEFAULT SEQ_BILLING.NEXTVAL	CONSTRAINT BILLING_PK PRIMARY KEY
	,FIXED_NO	        NUMBER          CONSTRAINT BILLING_FIXED_NO_NN NOT NULL
	,PLAN_CONTRACT_NO   NUMBER          CONSTRAINT BILLING_PLAN_CONTRACT_NO_NN NOT NULL
	,BILL_MONTH	        VARCHAR2(6)	CONSTRAINT BILL_MONTH_NN NOT NULL
	,BILL_TOTAL	        NUMBER	        DEFAULT 0
    ,ETC_BIL            NUMBER          DEFAULT 0
	,PAY_YN	            CHAR(1)	        DEFAULT 'N' CONSTRAINT BILL_PAY_YN_CK 	CHECK(PAY_YN IN ('Y', 'N'))
);

CREATE TABLE SERVICE_CONTRACT (
	NO	            NUMBER	        DEFAULT SEQ_SERVICE_CONTRACT.NEXTVAL CONSTRAINT SERVICE_CONTRACT_PK PRIMARY KEY
	,FIXED_NO	    NUMBER          CONSTRAINT SERVICE_CONTRACT_FIXED_NO_NN NOT NULL
	,SERVICE_NO	    NUMBER          CONSTRAINT SERVICE_CONTRACT_SERVICE_NO_NN NOT NULL
    ,BILL_NO	    NUMBER          
	,DEL_DATE	    TIMESTAMP       
	,USED_MONTH	    VARCHAR2(6)	DEFAULT TO_CHAR(SYSDATE, 'YYYYMM')
	,DISCOUNT_RATE	NUMBER	        DEFAULT 0
);

CREATE TABLE SERVICE_DELETE_CONFIRM(
    NO                      NUMBER      DEFAULT SEQ_SERVICE_DELETE_CONFIRM.NEXTVAL CONSTRAINT SERVICE_DELETE_CONFIRM_PK PRIMARY KEY
    ,EMPLOYEE_NO            NUMBER      
    ,SERVICE_CONTRACT_NO    NUMBER      CONSTRAINT SERVICE_DELETE_CONFIRM_SERVICE_CONTRACT_NO_NN NOT NULL 
    ,FIXED_NO               NUMBER      CONSTRAINT SERVICE_DELETE_CONFIRM_FIXED_NO_NN NOT NULL
    ,CONFIRM_AT             TIMESTAMP
    ,CONFIRM_STATUS         CHAR(1)     DEFAULT 'A' CONSTRAINT SERVICE_DELETE_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);

CREATE TABLE SERVICE_INSERT_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_SERVICE_INSERT_CONFIRM.NEXTVAL CONSTRAINT SERVICE_INSERT_CONFIRM_PK PRIMARY KEY
    ,EMPLOYEE_NO        NUMBER      
    ,SERVICE_NO         NUMBER      CONSTRAINT SERVICE_INSERT_CONFIRM_SERVICE_NO_NN NOT NULL 
    ,FIXED_NO           NUMBER      CONSTRAINT SERVICE_INSERT_CONFIRM_FIXED_NO_NN NOT NULL
    ,CONFIRM_AT         TIMESTAMP
    ,CONFIRM_STATUS     CHAR(1)     DEFAULT 'A' CONSTRAINT SERVICE_INSERT_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);

CREATE TABLE PLAN_CONTRACT(
    NO                  NUMBER  DEFAULT SEQ_PLAN_CONTRACT.NEXTVAL CONSTRAINT PLAN_CONTRACT_PK PRIMARY KEY
    , FIXED_NO          NUMBER  CONSTRAINT PLAN_CONTRACT_FIXED_NO_NN NOT NULL 
    , USED_DATA         NUMBER  DEFAULT 0
    , USED_VOICE        NUMBER  DEFAULT 0
    , USED_SMS          NUMBER  DEFAULT 0
    , USED_MONTH        CHAR(6) CONSTRAINT PLAN_CONTRACT_USED_MONTH_NN NOT NULL
    , PERSONAL_PLAN_NO  NUMBER  CONSTRAINT PLAN_CONTRACT_PERSONAL_PLAN_NO_NN NOT NULL 
);

CREATE TABLE FIXED_INFO(
    NO                          NUMBER      DEFAULT SEQ_FIXED_INFO.NEXTVAL CONSTRAINT FIXED_INFO_PK PRIMARY KEY
    , MEMBER_NO                 NUMBER      CONSTRAINT FIXED_INFO_MEMBER_NO_NN NOT NULL 
    , PHONE                     CHAR(11)    CONSTRAINT FIXED_INFO_PHONE_UQ UNIQUE CONSTRAINT FIXED_INFO_PHONE_CHK CHECK (LENGTH(PHONE) = 11)
    , CREATED_AT                TIMESTAMP   DEFAULT SYSDATE
    , DEL_AT                    TIMESTAMP
    , MAIN_CONTRACT_END_DATE    CHAR(8)     CONSTRAINT FIXED_INFO_MAIN_CONTRACT_END_DATE_CHK CHECK (LENGTH(MAIN_CONTRACT_END_DATE) = 8)
    , ACCOUNT_NO                NUMBER      CONSTRAINT FIXED_INFO_ACCOUNT_NO_NN NOT NULL 
    , MAIN_CONTRACT_NO          NUMBER      CONSTRAINT FIXED_INFO_MAIN_CONTRACT_NO_NN NOT NULL 
		, PLAN_NO                   NUMBER      CONSTRAINT FIXED_INFO_PLAN_NO_NN NOT NULL 
    , ACTIVE_YN                 CHAR(1)     DEFAULT 'N'	CONSTRAINT FIXED_INFO_ACTIVE_YN_NN NOT NULL CONSTRAINT FIXED_INFO_ACTIVE_YN_CK CHECK(ACTIVE_YN IN('Y','N'))
);
CREATE TABLE ACCOUNT(
    NO                  NUMBER  DEFAULT SEQ_ACCOUNT.NEXTVAL CONSTRAINT ACCOUNT_PK PRIMARY KEY
    , ACCOUNT_NUMBER    NUMBER  CONSTRAINT ACCOUNT_NUMBER_NO_NN NOT NULL 
    , PAYMENT_NO        NUMBER  CONSTRAINT ACCOUNT_PAYMENT_NO_NN NOT NULL 
);
CREATE TABLE PLAN_UPDATE_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_PLAN_UPDATE_CONFIRM.NEXTVAL CONSTRAINT PLAN_UPDATE_CONFIRM_PK PRIMARY KEY
    , EMPLOYEE_NO       NUMBER      
    , FIXED_NO          NUMBER      CONSTRAINT PLAN_UPDATE_CONFIRM_FIXED_NO_NN NOT NULL 
    , NEW_PLAN_NO       NUMBER      CONSTRAINT PLAN_UPDATE_CONFIRM_NEW_PLAN_NO_NN NOT NULL 
    , CONFIRM_AT        TIMESTAMP
    , CONFIRM_STATUS    CHAR(1)     DEFAULT 'A' CONSTRAINT PLAN_UPDATE_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);
CREATE TABLE PLAN_DELETE_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_PLAN_DELETE_CONFIRM.NEXTVAL CONSTRAINT PLAN_DELETE_CONFIRM_PK PRIMARY KEY
    , EMPLOYEE_NO       NUMBER      
    , FIXED_NO          NUMBER      CONSTRAINT PLAN_DELETE_CONFIRM_FIXED_NO_NN NOT NULL 
    , CONFIRM_AT        TIMESTAMP
    , CONFIRM_STATUS    CHAR(1)     DEFAULT 'A' CONSTRAINT PLAN_DELETE_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);
CREATE TABLE PLAN_INSERT_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_PLAN_INSERT_CONFIRM.NEXTVAL CONSTRAINT PLAN_INSERT_CONFIRM_PK PRIMARY KEY
    , EMPLOYEE_NO       NUMBER      
    , FIXED_NO          NUMBER      CONSTRAINT PLAN_INSERT_CONFIRM_FIXED_NO_NN NOT NULL 
    , CONFIRM_AT        TIMESTAMP
    , CONFIRM_STATUS    CHAR(1)     DEFAULT 'A' CONSTRAINT PLAN_INSERT_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);
CREATE TABLE MEMBER (
	NO	        NUMBER	            DEFAULT SEQ_MEMBER.NEXTVAL	PRIMARY KEY,
	ID	        VARCHAR2(100)		CONSTRAINT MEMBER_ID_NN NOT NULL CONSTRAINT MEMBER_ID_UQ UNIQUE,
	PW	        VARCHAR2(100)		CONSTRAINT MEMBER_PW_NN NOT NULL,
	NAME    	VARCHAR2(100)		CONSTRAINT MEMBER_NAME_NN NOT NULL,
	PHONE	    CHAR(11)		    CONSTRAINT MEMBER_PHONE_UQ UNIQUE,
	ADDRESS 	VARCHAR2(100)	    CONSTRAINT MEMBER_ADDRESS_NN NOT NULL,
	ADDRESS2 	VARCHAR2(100)	    ,
	EMAIL	    VARCHAR2(100)		CONSTRAINT MEMBER_EMAIL_NN NOT NULL CONSTRAINT MEMBER_EMAIL_UQ UNIQUE,
	RESIDENT	CHAR(13)		    CONSTRAINT MEMBER_RESIDENT_NN NOT NULL CONSTRAINT MEMBER_RESIDENT_UQ UNIQUE,
	CHANGE_NAME	VARCHAR2(1000)		,
	ORIGIN_NAME	VARCHAR2(1000)		,
	CREATED_AT	TIMESTAMP	        DEFAULT SYSDATE	CONSTRAINT MEMBER_CREATED_AT_NN NOT NULL,
	UPDATED_AT	TIMESTAMP	        ,
	QUIT_YN	    CHAR(1)	            DEFAULT 'N'	CONSTRAINT MEMBER_QUIT_YN_NN NOT NULL CONSTRAINT MEMBER_QUIT_YN_CK CHECK(QUIT_YN IN('Y','N'))
);
CREATE TABLE ATTENDANCE (
    USER_ID             NUMBER      
    , ATTEND_DATE       CHAR(8)     DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD')     
    ,CONSTRAINT ATTENDANCE_PK PRIMARY KEY (USER_ID, ATTEND_DATE)
);

--------------------------------------------------
-- 외래키 연결
--------------------------------------------------
ALTER TABLE EMPLOYEE
ADD 
(
CONSTRAINT EMPLOYEE_ANO_FK FOREIGN KEY (AGENCY_NO) REFERENCES AGENCY (NO)
, CONSTRAINT EMPLOYEE_JNO_FK FOREIGN KEY (JOB_NO) REFERENCES JOB (NO)
)
;
ALTER TABLE COUNSEL
ADD 
CONSTRAINT COUNSEL_MNO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO)
;
ALTER TABLE AGENCY
ADD 
CONSTRAINT AGENCY_MNO_FK FOREIGN KEY (MANAGER_NO) REFERENCES EMPLOYEE(NO)
;

ALTER TABLE PLAN
ADD 
CONSTRAINT PLAN_DATA_NO_FK   FOREIGN KEY (DATA_NO)   REFERENCES DATA_SPEED(NO)
;

ALTER TABLE QA
ADD 
CONSTRAINT QA_WNO_FK FOREIGN KEY (WRITER_NO) REFERENCES MEMBER (NO)
;

ALTER TABLE NOTICE
ADD 
CONSTRAINT NOTICE_WNO_FK FOREIGN KEY (WRITER_NO) REFERENCES EMPLOYEE (NO)
;
ALTER TABLE FAQ
ADD
CONSTRAINT FAQ_WNO_FK FOREIGN KEY (WRITER_NO) REFERENCES EMPLOYEE (NO)
;
ALTER TABLE QA_FILE
ADD
CONSTRAINT QA_FILE_QNO_FK FOREIGN KEY (QA_NO) REFERENCES QA(NO)
;
ALTER TABLE NOTICE_FILE
ADD
CONSTRAINT NOTICE_FILE_NNO_FK FOREIGN KEY (NOTICE_NO) REFERENCES NOTICE(NO)
;
ALTER TABLE REPLY
ADD
(
CONSTRAINT REPLY_ENO_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE (NO)
,CONSTRAINT REPLY_QNO_FK FOREIGN KEY (QA_NO) REFERENCES QA (NO)
)
;
ALTER TABLE BILLING 
ADD (
CONSTRAINT BILLING_FIXED_NO_FK             FOREIGN KEY (FIXED_NO)         REFERENCES FIXED_INFO (NO)
, CONSTRAINT BILLING_PLAN_CONTRACT_NO_FK    FOREIGN KEY (PLAN_CONTRACT_NO)  REFERENCES PLAN_CONTRACT (NO)
);

ALTER TABLE SERVICE_CONTRACT
ADD (
CONSTRAINT SERVICE_CONTRACT_FIXED_NO_FK     FOREIGN KEY (FIXED_NO)     REFERENCES FIXED_INFO (NO)
, CONSTRAINT SERVICE_CONTRACT_SERVICE_NO_FK  FOREIGN KEY (SERVICE_NO)    REFERENCES ADD_SERVICE (NO)
, CONSTRAINT SERVICE_CONTRACT_BILL_NO_FK     FOREIGN KEY (BILL_NO)       REFERENCES BILLING (NO)
);

ALTER TABLE SERVICE_DELETE_CONFIRM
ADD 
(
CONSTRAINT SERVICE_DELETE_CONFIRM_EMPLOYEE_NO_FK            FOREIGN KEY (EMPLOYEE_NO)           REFERENCES EMPLOYEE(NO)
, CONSTRAINT SERVICE_DELETE_CONFIRM_SERVICE_CONTRACT_NO_FK  FOREIGN KEY (SERVICE_CONTRACT_NO)   REFERENCES SERVICE_CONTRACT(NO)
, CONSTRAINT SERVICE_DELETE_CONFIRM_FIXED_NO_FK        FOREIGN KEY (FIXED_NO)         REFERENCES FIXED_INFO(NO)
);

ALTER TABLE SERVICE_INSERT_CONFIRM
ADD 
(
CONSTRAINT SERVICE_INSERT_CONFIRM_EMPLOYEE_NO_FK        FOREIGN KEY (EMPLOYEE_NO)   REFERENCES EMPLOYEE(NO)
, CONSTRAINT SERVICE_INSERT_CONFIRM_SERVICE_NO_FK       FOREIGN KEY (SERVICE_NO)    REFERENCES ADD_SERVICE(NO)
, CONSTRAINT SERVICE_INSERT_CONFIRM_FIXED_NO_FK    FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
);

ALTER TABLE PLAN_CONTRACT
ADD 
(
CONSTRAINT PLAN_CONTRACT_FIXED_NO_FK FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
, CONSTRAINT PLAN_CONTRACT_PERSONAL_PLAN_NO_FK FOREIGN KEY (PERSONAL_PLAN_NO) REFERENCES PLAN(NO)
)
;
ALTER TABLE FIXED_INFO
ADD 
(
CONSTRAINT FIXED_INFO_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(NO)
, CONSTRAINT FIXED_INFO_ACCOUNT_NO_FK FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(NO)
, CONSTRAINT FIXED_INFO_MAIN_CONTRACT_NO_FK FOREIGN KEY (MAIN_CONTRACT_NO) REFERENCES MAIN_CONTRACT(NO)
, CONSTRAINT FIXED_INFO_PLAN_NO_FK FOREIGN KEY (PLAN_NO) REFERENCES PLAN(NO)
)
;
ALTER TABLE ACCOUNT
ADD 
(
CONSTRAINT ACCOUNT_PAYMENT_NO_FK FOREIGN KEY (PAYMENT_NO) REFERENCES PAYMENT(NO)
)
;
ALTER TABLE PLAN_UPDATE_CONFIRM
ADD 
(
CONSTRAINT PLAN_UPDATE_CONFIRM_EMPLOYEE_NO_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE(NO)
, CONSTRAINT PLAN_UPDATE_CONFIRM_FIXED_NO_FK FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
, CONSTRAINT PLAN_UPDATE_CONFIRM_PLAN_NO_FK FOREIGN KEY (NEW_PLAN_NO) REFERENCES PLAN(NO)
)
;
ALTER TABLE PLAN_DELETE_CONFIRM
ADD 
(
CONSTRAINT PLAN_DELETE_CONFIRM_EMPLOYEE_NO_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE(NO)
, CONSTRAINT PLAN_DELETE_CONFIRM_FIXED_NO_FK FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
)
;
ALTER TABLE PLAN_INSERT_CONFIRM
ADD 
(
CONSTRAINT PLAN_INSERT_CONFIRM_EMPLOYEE_NO_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE(NO)
, CONSTRAINT PLAN_INSERT_CONFIRM_FIXED_NO_FK FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
)
;
ALTER TABLE ATTENDANCE
ADD 
CONSTRAINT ATTENDANCE_MNO_FK FOREIGN KEY (USER_ID) REFERENCES MEMBER(NO)
;

-------------------------
--코멘트
-------------------------


COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "BILLING"."NO" IS '청구넘버';
COMMENT ON COLUMN "BILLING"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "BILLING"."PLAN_CONTRACT_NO" IS '사용내역 번호';
COMMENT ON COLUMN "BILLING"."BILL_MONTH" IS '청구월';
COMMENT ON COLUMN "BILLING"."BILL_TOTAL" IS '총청구금액';
COMMENT ON COLUMN "BILLING"."PAY_YN" IS '수납상태';
COMMENT ON COLUMN "BILLING"."ETC_BIL" IS '추가청구금액';

COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."NEW_PLAN_NO" IS '바꿀요금제번호';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "JOB"."NO" IS '직급번호';
COMMENT ON COLUMN "JOB"."JOB_NAME" IS '직급명';

COMMENT ON COLUMN "NOTICE"."NO" IS '글 번호';
COMMENT ON COLUMN "NOTICE"."WRITER_NO" IS '작성자 번호';
COMMENT ON COLUMN "NOTICE"."TITLE" IS '제목';
COMMENT ON COLUMN "NOTICE"."CONTENT" IS '내용';
COMMENT ON COLUMN "NOTICE"."HIT" IS '조회수';
COMMENT ON COLUMN "NOTICE"."CREATED_AT" IS '작성일시';
COMMENT ON COLUMN "NOTICE"."UPDATED_AT" IS '수정일시';
COMMENT ON COLUMN "NOTICE"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "SERVICE_CONTRACT"."NO" IS '계약 번호';
COMMENT ON COLUMN "SERVICE_CONTRACT"."BILL_NO" IS '청구넘버';
COMMENT ON COLUMN "SERVICE_CONTRACT"."SERVICE_NO" IS '서비스 번호';
COMMENT ON COLUMN "SERVICE_CONTRACT"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "SERVICE_CONTRACT"."USED_MONTH" IS '사용년월';
COMMENT ON COLUMN "SERVICE_CONTRACT"."DISCOUNT_RATE" IS '할인률';
COMMENT ON COLUMN "SERVICE_CONTRACT"."DEL_DATE" IS '해지날짜';

COMMENT ON COLUMN "QA_FILE"."NO" IS '파일번호';
COMMENT ON COLUMN "QA_FILE"."NAME" IS '파일이름';
COMMENT ON COLUMN "QA_FILE"."URL" IS '파일경로';
COMMENT ON COLUMN "QA_FILE"."ORIGIN_NAME" IS '원본파일명';
COMMENT ON COLUMN "QA_FILE"."QA_NO" IS '문의번호';

COMMENT ON COLUMN "QA"."NO" IS '문의번호';
COMMENT ON COLUMN "QA"."TITLE" IS '제목';
COMMENT ON COLUMN "QA"."CONTENT" IS '내용';
COMMENT ON COLUMN "QA"."CATEGORY" IS '카테고리';
COMMENT ON COLUMN "QA"."CREATED_AT" IS '등록날짜';
COMMENT ON COLUMN "QA"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "QA"."WRITER_NO" IS '작성자번호';
COMMENT ON COLUMN "QA"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "ACCOUNT"."NO" IS '결제수단 번호';
COMMENT ON COLUMN "ACCOUNT"."ACCOUNT_NUMBER" IS '식별번호';
COMMENT ON COLUMN "ACCOUNT"."PAYMENT_NO" IS '결제사번호';

COMMENT ON COLUMN "COUNSEL"."NO" IS '상담번호';
COMMENT ON COLUMN "COUNSEL"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "COUNSEL"."CONTENT" IS '내용요약';
COMMENT ON COLUMN "COUNSEL"."COUNSEL_DATE" IS '상담날짜';
COMMENT ON COLUMN "COUNSEL"."WRITER_NO" IS '작성직원';

COMMENT ON COLUMN "MAIN_CONTRACT"."NO" IS '약정번호';
COMMENT ON COLUMN "MAIN_CONTRACT"."TERM" IS '약정기간';
COMMENT ON COLUMN "MAIN_CONTRACT"."DISCOUNT_RATE" IS '할인율';
COMMENT ON COLUMN "MAIN_CONTRACT"."PENALTY" IS '위약금비율';

COMMENT ON COLUMN "MEMBER"."NO" IS '회원번호';
COMMENT ON COLUMN "MEMBER"."ID" IS '아이디';
COMMENT ON COLUMN "MEMBER"."PW" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."NAME" IS '이름';
COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';
COMMENT ON COLUMN "MEMBER"."ADDRESS2" IS '상세주소';
COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';
COMMENT ON COLUMN "MEMBER"."RESIDENT" IS '주민등록번호';
COMMENT ON COLUMN "MEMBER"."CHANGE_NAME" IS '신분증이름';
COMMENT ON COLUMN "MEMBER"."ORIGIN_NAME" IS '신분증원본이름';
COMMENT ON COLUMN "MEMBER"."CREATED_AT" IS '가입날짜';
COMMENT ON COLUMN "MEMBER"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "MEMBER"."QUIT_YN" IS '탈퇴여부';

COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."SERVICE_CONTRACT_NO" IS '계약 번호';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "PLAN_CONTRACT"."NO" IS '사용내역 번호';
COMMENT ON COLUMN "PLAN_CONTRACT"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "PLAN_CONTRACT"."USED_DATA" IS '사용데이터양';
COMMENT ON COLUMN "PLAN_CONTRACT"."USED_VOICE" IS '사용한전화(분)';
COMMENT ON COLUMN "PLAN_CONTRACT"."USED_SMS" IS '사용한문자횟수';
COMMENT ON COLUMN "PLAN_CONTRACT"."USED_MONTH" IS '사용년월';
COMMENT ON COLUMN "PLAN_CONTRACT"."PERSONAL_PLAN_NO" IS '요금제번호';

COMMENT ON COLUMN "DATA_SPEED"."NO" IS '속도번호';
COMMENT ON COLUMN "DATA_SPEED"."SPEED" IS '소진전 속도';
COMMENT ON COLUMN "DATA_SPEED"."DONE_SPEED" IS '소진후 속도';

COMMENT ON COLUMN "PLAN"."NO" IS '요금제번호';
COMMENT ON COLUMN "PLAN"."NAME" IS '요금제의 이름';
COMMENT ON COLUMN "PLAN"."PRICE" IS '요금제의 가격';
COMMENT ON COLUMN "PLAN"."DATA_TOTAL" IS '요금제의 종류마다 다른 총데이터양';
COMMENT ON COLUMN "PLAN"."VOICE_TOTAL" IS '기본 전화가능 시간(분)';
COMMENT ON COLUMN "PLAN"."SMS_TOTAL" IS '문자가능기본횟수';
COMMENT ON COLUMN "PLAN"."SELL_YN" IS '요금제의 판매 상황';
COMMENT ON COLUMN "PLAN"."DATA_NO" IS '속도번호';
COMMENT ON COLUMN "PLAN"."DATA_SHARE" IS '공유데이터';
COMMENT ON COLUMN "PLAN"."CATEGORY" IS '카테고리';
COMMENT ON COLUMN "PLAN"."DESCRIPTION" IS '설명';

COMMENT ON COLUMN "AGENCY"."NO" IS '대리점 넘버';
COMMENT ON COLUMN "AGENCY"."MANAGER_NO" IS '본사관리자 번호';
COMMENT ON COLUMN "AGENCY"."NAME" IS '대리점 이름';
COMMENT ON COLUMN "AGENCY"."ADDRESS" IS '주소';
COMMENT ON COLUMN "AGENCY"."PHONE" IS '연락처';
COMMENT ON COLUMN "AGENCY"."CREATED_AT" IS '등록날짜';
COMMENT ON COLUMN "AGENCY"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "AGENCY"."QUIT_YN" IS '폐점여부';

COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."SERVICE_NO" IS '서비스 번호';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "NOTICE_FILE"."NO" IS '파일번호';
COMMENT ON COLUMN "NOTICE_FILE"."NAME" IS '파일이름';
COMMENT ON COLUMN "NOTICE_FILE"."URL" IS '파일경로';
COMMENT ON COLUMN "NOTICE_FILE"."ORIGIN_NAME" IS '원본파일명';
COMMENT ON COLUMN "NOTICE_FILE"."NOTICE_NO" IS '글 번호';

COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "REPLY"."NO" IS '문의답글 번호';
COMMENT ON COLUMN "REPLY"."CONTENT" IS '내용';
COMMENT ON COLUMN "REPLY"."CREATED_AT" IS '등록날짜';
COMMENT ON COLUMN "REPLY"."EMPLOYEE_NO" IS '직원번호';
COMMENT ON COLUMN "REPLY"."QA_NO" IS '문의번호';

COMMENT ON COLUMN "FIXED_INFO"."NO" IS '가입정보 번호';
COMMENT ON COLUMN "FIXED_INFO"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "FIXED_INFO"."PHONE" IS '개통된 전화번호';
COMMENT ON COLUMN "FIXED_INFO"."CREATED_AT" IS '요금제 가입날짜';
COMMENT ON COLUMN "FIXED_INFO"."DEL_AT" IS '해지날짜';
COMMENT ON COLUMN "FIXED_INFO"."MAIN_CONTRACT_END_DATE" IS '약정종료날짜';
COMMENT ON COLUMN "FIXED_INFO"."ACCOUNT_NO" IS '결제수단 번호';
COMMENT ON COLUMN "FIXED_INFO"."MAIN_CONTRACT_NO" IS '약정번호';
COMMENT ON COLUMN "FIXED_INFO"."PLAN_NO" IS '요금제번호';
COMMENT ON COLUMN "FIXED_INFO"."ACTIVE_YN" IS '활성화여부';

COMMENT ON COLUMN "FAQ"."NO" IS 'PK';
COMMENT ON COLUMN "FAQ"."QUESTION" IS '질문';
COMMENT ON COLUMN "FAQ"."ANSWER" IS '답변';
COMMENT ON COLUMN "FAQ"."WRITER_NO" IS '작성자 번호';
COMMENT ON COLUMN "FAQ"."DEL_YN" IS '삭제여부';
COMMENT ON COLUMN "FAQ"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "FAQ"."CREATED_AT" IS '생성날짜';

COMMENT ON COLUMN "EMPLOYEE"."NO" IS '직원번호';
COMMENT ON COLUMN "EMPLOYEE"."AGENCY_NO" IS '대리점 넘버';
COMMENT ON COLUMN "EMPLOYEE"."ID" IS '아이디';
COMMENT ON COLUMN "EMPLOYEE"."PW" IS '비밀번호';
COMMENT ON COLUMN "EMPLOYEE"."NAME" IS '이름';
COMMENT ON COLUMN "EMPLOYEE"."PHONE" IS '전화번호';
COMMENT ON COLUMN "EMPLOYEE"."ADDRESS" IS '주소';
COMMENT ON COLUMN "EMPLOYEE"."ADDRESS2" IS '상세주소';
COMMENT ON COLUMN "EMPLOYEE"."EMAIL" IS '이메일';
COMMENT ON COLUMN "EMPLOYEE"."RESIDENT" IS '주민번호';
COMMENT ON COLUMN "EMPLOYEE"."JOB_NO" IS '직급번호';
COMMENT ON COLUMN "EMPLOYEE"."SALARY" IS '월급';
COMMENT ON COLUMN "EMPLOYEE"."CREATED_AT" IS '입사날짜';
COMMENT ON COLUMN "EMPLOYEE"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "EMPLOYEE"."QUIT_YN" IS '퇴사여부';
COMMENT ON COLUMN "EMPLOYEE"."PROFILE_CHANGE_NAME" IS '프로필이름';
COMMENT ON COLUMN "EMPLOYEE"."PROFILE_ORIGIN_NAME" IS '프로필원본이름';

COMMENT ON COLUMN "ADD_SERVICE"."NO" IS '서비스 번호';
COMMENT ON COLUMN "ADD_SERVICE"."SERVICE" IS '서비스명';
COMMENT ON COLUMN "ADD_SERVICE"."CONTENT" IS '내용';
COMMENT ON COLUMN "ADD_SERVICE"."PRICE" IS '가격';
COMMENT ON COLUMN "ADD_SERVICE"."SELL_YN" IS '판매여부';
COMMENT ON COLUMN "ADD_SERVICE"."CREATED_AT" IS '생성일자';
COMMENT ON COLUMN "ADD_SERVICE"."CATEGORY" IS '카테고리';

COMMENT ON COLUMN "PAYMENT"."NO" IS '결제사 번호';
COMMENT ON COLUMN "PAYMENT"."NAME" IS '결제사 이름';


------------------------------
--더미 데이터
------------------------------

INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('5G', '400Kbps');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('5G', '1Mbps');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('5G', '3Mbps');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('5G', '5Mbps');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('5G', '무제한');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('LTE', '400Kbps');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('LTE', '1Mbps');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('LTE', '3Mbps');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('LTE', '5Mbps');
INSERT INTO DATA_SPEED (SPEED, DONE_SPEED) VALUES('LTE', '무제한');

INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 스페셜',89000,'150GB','집/이동전화 무제한','무제한','Y',4,'80GB','normal','영상과 게임을 즐기기에 충분한 대용량 데이터 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 플러스',79000,'130GB','집/이동전화 무제한','무제한','Y',4,'70GB','normal','넉넉한 데이터를 제공하는 5G 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 스마트',69000,'90GB','집/이동전화 무제한','무제한','Y',3,'40GB','normal','데이터와 통화를 균형 있게 제공하는 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 데이터',65000,'80GB','집/이동전화 무제한','무제한','Y',3,'35GB','normal','일반 사용자에게 적합한 데이터 중심 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 밸런스',63000,'75GB','집/이동전화 무제한','무제한','Y',3,'30GB','normal','데이터와 통화를 균형 있게 제공');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 스탠다드',61000,'70GB','집/이동전화 무제한','무제한','Y',3,'30GB','normal','합리적인 가격의 5G 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 베이직+',59000,'70GB','집/이동전화 무제한','무제한','Y',2,'30GB','normal','기본적인 데이터 사용자를 위한 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 베이직',55000,'50GB','집/이동전화 무제한','무제한','Y',2,'20GB','normal','가성비 좋은 5G 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 라이트',49000,'30GB','집/이동전화 무제한','무제한','Y',2,'10GB','normal','가볍게 사용하는 5G 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 세이브',47000,'25GB','집/이동전화 무제한','무제한','Y',2,'10GB','normal','합리적인 가격의 5G 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 미니',39000,'15GB','집/이동전화 무제한','무제한','Y',1,'5GB','normal','부담 없는 가격의 5G 입문 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 스타터',33000,'10GB','집/이동전화 무제한','무제한','Y',1,'3GB','normal','가볍게 시작하는 5G 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 라이트 미니',31000,'8GB','집/이동전화 무제한','무제한','Y',1,'2GB','normal','소량 데이터 사용자 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 엔트리',29000,'6GB','집/이동전화 무제한','무제한','Y',1,'2GB','normal','초보 사용자용 5G 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 비즈니스',75000,'150GB','집/이동전화 무제한','무제한','Y',10,'80GB','normal','업무용 LTE 데이터 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 패밀리',72000,'140GB','집/이동전화 무제한','무제한','Y',10,'70GB','normal','가족 데이터 공유 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 스페셜',69000,'120GB','집/이동전화 무제한','무제한','Y',9,'50GB','normal','영상 시청에 적합한 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 플러스',59000,'80GB','집/이동전화 무제한','무제한','Y',9,'30GB','normal','넉넉한 데이터를 제공하는 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 스트리밍',64000,'90GB','집/이동전화 무제한','무제한','Y',9,'40GB','normal','영상 스트리밍 이용 고객을 위한 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 게임',62000,'85GB','집/이동전화 무제한','무제한','Y',9,'35GB','normal','게임 이용 고객에게 적합한 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 스마트',49000,'50GB','집/이동전화 무제한','무제한','Y',8,'20GB','normal','일상적인 데이터 사용에 적합');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 밸런스',47000,'45GB','집/이동전화 무제한','무제한','Y',8,'18GB','normal','균형 잡힌 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 데이터',45000,'40GB','집/이동전화 무제한','무제한','Y',8,'15GB','normal','데이터 중심 사용자 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 스탠다드',43000,'35GB','집/이동전화 무제한','무제한','Y',8,'15GB','normal','합리적인 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 베이직+',41000,'30GB','집/이동전화 무제한','무제한','Y',7,'12GB','normal','기본적인 LTE 데이터 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 베이직',39000,'25GB','집/이동전화 무제한','무제한','Y',7,'10GB','normal','가성비 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 라이트',33000,'15GB','집/이동전화 무제한','무제한','Y',7,'5GB','normal','가볍게 사용하는 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 세이브',31000,'12GB','집/이동전화 무제한','무제한','Y',7,'4GB','normal','저렴한 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 미니',29000,'10GB','집/이동전화 무제한','무제한','Y',6,'3GB','normal','최소 데이터 사용자 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 스타터',27000,'8GB','집/이동전화 무제한','무제한','Y',6,'2GB','normal','입문용 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 라이트 미니',25000,'6GB','집/이동전화 무제한','무제한','Y',6,'2GB','normal','소량 데이터 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 엔트리',23000,'5GB','집/이동전화 무제한','무제한','Y',6,'1GB','normal','가장 기본적인 LTE 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 울트라',130000,'무제한','집/이동전화 무제한','무제한','Y',5,'150GB','popularity','최고 성능의 5G 프리미엄 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 맥스',120000,'무제한','집/이동전화 무제한','무제한','Y',5,'120GB','popularity','초고속 5G 데이터를 마음껏 사용할 수 있는 프리미엄 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 프라임',110000,'무제한','집/이동전화 무제한','무제한','Y',5,'110GB','popularity','대용량 데이터와 안정적인 속도를 제공하는 5G 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 프리미엄',100000,'무제한','집/이동전화 무제한','무제한','Y',5,'100GB','popularity','프리미엄 고객을 위한 5G 데이터 무제한 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 울트라',90000,'200GB','집/이동전화 무제한','무제한','Y',10,'100GB','popularity','LTE 환경에서 최대 데이터 제공');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'LTE 프리미엄',79000,'무제한','집/이동전화 무제한','무제한','Y',10,'60GB','popularity','LTE 데이터 무제한 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 스트리밍',82000,'140GB','집/이동전화 무제한','무제한','Y',4,'70GB','new','영상 스트리밍 이용 고객을 위한 요금제');
INSERT INTO PLAN VALUES (SEQ_PLAN.NEXTVAL,'5G 게임',78000,'120GB','집/이동전화 무제한','무제한','Y',4,'60GB','new','게임 이용에 최적화된 데이터 요금제');

INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('데이터 1GB 추가','데이터를 1GB 추가로 제공하는 서비스',3000,'DATA');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('데이터 3GB 추가','데이터를 3GB 추가로 제공하는 서비스',7000,'DATA');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('데이터 5GB 추가','데이터를 5GB 추가로 제공하는 서비스',9000,'DATA');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('데이터 10GB 추가','데이터를 10GB 추가로 제공하는 서비스',15000,'DATA');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('데이터 하루 무제한','하루 동안 데이터를 무제한으로 사용할 수 있는 서비스',5000,'DATA');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('야간 데이터 무제한','매일 밤 12시~아침 7시 데이터 무제한 제공',4000,'DATA');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('넷플릭스 베이직','넷플릭스 베이직 요금제 이용권 제공',9500,'OTT');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('넷플릭스 스탠다드','넷플릭스 스탠다드 요금제 이용권 제공',13500,'OTT');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('유튜브 프리미엄','광고 없이 유튜브 시청 및 백그라운드 재생 제공',10450,'OTT');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('멜론 스트리밍','멜론 음악 스트리밍 이용권 제공',7900,'OTT');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('웨이브 이용권','웨이브 OTT 콘텐츠 이용 서비스',7900,'OTT');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('티빙 이용권','티빙 OTT 콘텐츠 이용 서비스',7900,'OTT');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('스팸 전화 차단','스팸 전화 및 문자를 자동으로 차단',1000,'SECURITY');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('보이스피싱 보호','의심 전화 알림 및 차단 기능 제공',2000,'SECURITY');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('모바일 백신','스마트폰 악성코드 및 바이러스 보호 서비스',2500,'SECURITY');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('안심번호 서비스','개인 번호 대신 가상번호를 제공하는 서비스',1500,'SECURITY');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('휴대폰 위치 찾기','휴대폰 분실 시 위치를 확인할 수 있는 서비스',2000,'SECURITY');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('개인정보 보호','개인정보 유출 모니터링 서비스',3000,'SECURITY');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('스마트폰 파손 보험','스마트폰 파손 시 수리비 일부 보장',7900,'INSURANCE');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('스마트폰 분실 보험','휴대폰 분실 시 보상 또는 교체 지원',9900,'INSURANCE');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('프리미엄 단말 보험','파손, 침수, 분실을 모두 보장하는 보험',12900,'INSURANCE');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('아이폰 전용 보험','아이폰 단말 전용 보험 서비스',13900,'INSURANCE');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('갤럭시 전용 보험','갤럭시 단말 전용 보험 서비스',12900,'INSURANCE');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('고급 스마트폰 보험','고가 스마트폰 전용 프리미엄 보험',15900,'INSURANCE');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('로밍 데이터 1일권','해외에서 하루 동안 데이터를 이용',11000,'ROAMING');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('로밍 데이터 3일권','해외에서 3일 동안 데이터를 이용',29000,'ROAMING');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('로밍 데이터 7일권','해외에서 7일 동안 데이터를 이용',39000,'ROAMING');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('로밍 데이터 30일권','해외 장기 여행자를 위한 데이터 서비스',89000,'ROAMING');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('로밍 데이터 무제한','해외에서 데이터를 무제한으로 사용',99000,'ROAMING');
INSERT INTO ADD_SERVICE (SERVICE, CONTENT, PRICE, CATEGORY) VALUES ('로밍 음성 할인','해외 통화 요금 할인 서비스',5000,'ROAMING');

INSERT INTO PAYMENT (NAME) VALUES ('가온은행');
INSERT INTO PAYMENT (NAME) VALUES ('누리은행');
INSERT INTO PAYMENT (NAME) VALUES ('다온은행');
INSERT INTO PAYMENT (NAME) VALUES ('라온은행');
INSERT INTO PAYMENT (NAME) VALUES ('미래은행');
INSERT INTO PAYMENT (NAME) VALUES ('하나온은행');
INSERT INTO PAYMENT (NAME) VALUES ('대한은행');
INSERT INTO PAYMENT (NAME) VALUES ('중앙은행');
INSERT INTO PAYMENT (NAME) VALUES ('동양은행');
INSERT INTO PAYMENT (NAME) VALUES ('서광은행');
INSERT INTO PAYMENT (NAME) VALUES ('가온카드');
INSERT INTO PAYMENT (NAME) VALUES ('누리카드');
INSERT INTO PAYMENT (NAME) VALUES ('다온카드');
INSERT INTO PAYMENT (NAME) VALUES ('라온카드');
INSERT INTO PAYMENT (NAME) VALUES ('미래카드');
INSERT INTO PAYMENT (NAME) VALUES ('대한카드');
INSERT INTO PAYMENT (NAME) VALUES ('중앙카드');
INSERT INTO PAYMENT (NAME) VALUES ('동양카드');
INSERT INTO PAYMENT (NAME) VALUES ('서광카드');
INSERT INTO PAYMENT (NAME) VALUES ('한빛카드');
INSERT INTO PAYMENT (NAME) VALUES ('스마트페이');
INSERT INTO PAYMENT (NAME) VALUES ('유니온페이');
INSERT INTO PAYMENT (NAME) VALUES ('코리아페이');
INSERT INTO PAYMENT (NAME) VALUES ('모바일페이');
INSERT INTO PAYMENT (NAME) VALUES ('스피드페이');
INSERT INTO PAYMENT (NAME) VALUES ('제로페이');
INSERT INTO PAYMENT (NAME) VALUES ('클라우드페이');
INSERT INTO PAYMENT (NAME) VALUES ('이지페이');
INSERT INTO PAYMENT (NAME) VALUES ('원페이');
INSERT INTO PAYMENT (NAME) VALUES ('플러스페이');
INSERT INTO PAYMENT (NAME) VALUES ('가온증권');
INSERT INTO PAYMENT (NAME) VALUES ('누리증권');
INSERT INTO PAYMENT (NAME) VALUES ('다온증권');
INSERT INTO PAYMENT (NAME) VALUES ('라온증권');
INSERT INTO PAYMENT (NAME) VALUES ('대한증권');
INSERT INTO PAYMENT (NAME) VALUES ('중앙증권');
INSERT INTO PAYMENT (NAME) VALUES ('동양증권');
INSERT INTO PAYMENT (NAME) VALUES ('서광증권');
INSERT INTO PAYMENT (NAME) VALUES ('한빛증권');
INSERT INTO PAYMENT (NAME) VALUES ('미래증권');

INSERT INTO MAIN_CONTRACT (TERM, DISCOUNT_RATE, PENALTY) VALUES ('12', 10, 30);
INSERT INTO MAIN_CONTRACT (TERM, DISCOUNT_RATE, PENALTY) VALUES ('24', 20, 40);
INSERT INTO MAIN_CONTRACT (TERM, DISCOUNT_RATE, PENALTY) VALUES ('36', 25, 50);

INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user001', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '김민수', '01050000001', '서울시 강남구 테헤란로 11', '101동 101호', 'user001@test.com', '9001011000001');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user002', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '이지영', '01050000002', '서울시 서초구 서초대로 22', '자이아파트 202동 202호', 'user002@test.com', '9202022000002');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user003', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '박서준', '01050000003', '서울시 송파구 올림픽로 33', '래미안 303동 303호', 'user003@test.com', '8803031000003');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user004', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '최지은', '01050000004', '경기도 성남시 분당구 44', '푸르지오 404동 404호', 'user004@test.com', '9504042000004');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user005', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '정도윤', '01050000005', '경기도 용인시 수지구 55', '힐스테이트 505동 505호', 'user005@test.com', '9105051000005');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user006', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '강하은', '01050000006', '서울시 강동구 천호대로 66', '롯데캐슬 606동 606호', 'user006@test.com', '9606062000006');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user007', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '조시우', '01050000007', '서울시 마포구 월드컵로 77', '아이파크 707동 707호', 'user007@test.com', '8907071000007');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user008', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '윤서연', '01050000008', '서울시 종로구 세종대로 88', '2층 201호', 'user008@test.com', '9308082000008');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user009', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '장지훈', '01050000009', '서울시 용산구 이태원로 99', '3층 302호', 'user009@test.com', '9009091000009');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user010', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '임수아', '01050000010', '서울시 광진구 아차산로 10', 'A동 401호', 'user010@test.com', '9410102000010');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user011', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '한우진', '01050000011', '인천시 연수구 컨벤시아대로 11', 'B동 502호', 'user011@test.com', '8511111000011');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user012', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '오유진', '01050000012', '부산시 해운대구 달맞이길 12', '센트럴파크 101동 1201호', 'user012@test.com', '9712122000012');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user013', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '신도현', '01050000013', '대구시 수성구 동대구로 13', '더샵 102동 1302호', 'user013@test.com', '9101131000013');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user014', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '서하린', '01050000014', '대전시 유성구 대학로 14', 'SK뷰 103동 1403호', 'user014@test.com', '9502142000014');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user015', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '권준서', '01050000015', '광주시 서구 상무대로 15', '호반베르디움 104동 1504호', 'user015@test.com', '8803151000015');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user016', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '황지아', '01050000016', '울산시 남구 삼산로 16', '101동 1601호', 'user016@test.com', '9204162000016');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user017', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '안도윤', '01050000017', '제주시 노형로 17', '201동 1702호', 'user017@test.com', '9005171000017');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user018', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '송아인', '01050000018', '수원시 팔달구 매산로 18', '301동 1803호', 'user018@test.com', '9606182000018');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user019', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '전민재', '01050000019', '고양시 일산동구 정발산로 19', '일산위브 401동 1904호', 'user019@test.com', '8907191000019');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user020', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '홍유나', '01050000020', '창원시 성산구 원이대로 20', '501동 2005호', 'user020@test.com', '9408202000020');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user021', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '고시윤', '01050000021', '서울시 영등포구 여의대로 21', '여의도자이 101동 2101호', 'user021@test.com', '8709211000021');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user022', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '문시아', '01050000022', '서울시 구로구 디지털로 22', '구로디지털 102동 2202호', 'user022@test.com', '9810222000022');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user023', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '양준호', '01050000023', '서울시 동작구 노량진로 23', '동작래미안 103동 2303호', 'user023@test.com', '9111231000023');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user024', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '손지유', '01050000024', '서울시 관악구 남부순환로 24', '104동 2404호', 'user024@test.com', '9512242000024');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user025', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '배건우', '01050000025', '서울시 성동구 왕십리로 25', '성동푸르지오 105동 2505호', 'user025@test.com', '8901251000025');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user026', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '백다은', '01050000026', '서울시 성북구 보문로 26', '보문파크뷰 106동 2606호', 'user026@test.com', '9202262000026');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user027', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '허은우', '01050000027', '서울시 동대문구 천호대로 27', '청량리역롯데캐슬 107동 2707호', 'user027@test.com', '9003271000027');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user028', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '남소율', '01050000028', '서울시 중랑구 망우로 28', '상봉프레미어스 108동 2808호', 'user028@test.com', '9604282000028');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user029', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '심재윤', '01050000029', '서울시 노원구 동일로 29', '노원센트럴 109동 2909호', 'user029@test.com', '8805291000029');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user030', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '노하윤', '01050000030', '서울시 강북구 도봉로 30', '미아래미안 110동 3010호', 'user030@test.com', '9306302000030');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user031', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '곽도훈', '01050000031', '서울시 은평구 통일로 31', '은평뉴타운 111동 3111호', 'user031@test.com', '9107011000031');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user032', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '성지안', '01050000032', '서울시 서대문구 신촌로 32', '신촌푸르지오 112동 3212호', 'user032@test.com', '9508022000032');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user033', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '차우진', '01050000033', '서울시 양천구 목동로 33', '목동센트럴 113동 3313호', 'user033@test.com', '8909031000033');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user034', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '우서윤', '01050000034', '서울시 강서구 공항대로 34', '마곡엠밸리 114동 3414호', 'user034@test.com', '9410042000034');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user035', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '구하준', '01050000035', '부천시 길주로 35', '중동센트럴파크 115동 3515호', 'user035@test.com', '9011051000035');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user036', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '신아린', '01050000036', '안양시 동안구 시민대로 36', '평촌더샵 116동 3616호', 'user036@test.com', '9712062000036');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user037', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '임건우', '01050000037', '안산시 단원구 중앙대로 37', '안산푸르지오 117동 3717호', 'user037@test.com', '8801071000037');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user038', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '전지우', '01050000038', '남양주시 경춘로 38', '다산자이 118동 3818호', 'user038@test.com', '9302082000038');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user039', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '류준영', '01050000039', '평택시 평택로 39', '고덕파라곤 119동 3919호', 'user039@test.com', '9103091000039');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user040', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '강소율', '01050000040', '파주시 평화로 40', '운정센트럴 120동 4020호', 'user040@test.com', '9504102000040');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user041', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '오승우', '01050000041', '시흥시 시흥대로 41', '배곧스카이 121동 4121호', 'user041@test.com', '8905111000041');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user042', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '한채원', '01050000042', '김포시 김포대로 42', '걸포메트로자이 122동 4222호', 'user042@test.com', '9606122000042');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user043', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '권민찬', '01050000043', '화성시 동탄대로 43', '동탄린스트라우스 123동 4323호', 'user043@test.com', '9007131000043');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user044', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '황서현', '01050000044', '포항시 남구 포스코대로 44', '포항자이 124동 4424호', 'user044@test.com', '9208142000044');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user045', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '송연우', '01050000045', '구미시 구미대로 45', '구미아이파크 125동 4525호', 'user045@test.com', '8709151000045');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user046', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '안예은', '01050000046', '진주시 진주대로 46', '진주혁신도시 126동 4626호', 'user046@test.com', '9410162000046');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user047', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '조현우', '01050000047', '원주시 원일로 47', '원주기업도시 127동 4727호', 'user047@test.com', '9111171000047');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user048', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '윤다인', '01050000048', '춘천시 영서로 48', '춘천센트럴 128동 4828호', 'user048@test.com', '9812182000048');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user049', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '최도현', '01050000049', '강릉시 경강로 49', '강릉유천 129동 4929호', 'user049@test.com', '8901191000049');
INSERT INTO MEMBER (ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, RESIDENT) VALUES ('user050', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '이서아', '01050000050', '천안시 서북구 번영로 50', '천안불당지웰 130동 5030호', 'user050@test.com', '9502202000050');

INSERT INTO JOB (JOB_NAME) VALUES ('사원');
INSERT INTO JOB (JOB_NAME) VALUES ('관리자');
INSERT INTO JOB (JOB_NAME) VALUES ('점장');
INSERT INTO JOB (JOB_NAME) VALUES ('부점장');
INSERT INTO JOB (JOB_NAME) VALUES ('상담원');
INSERT INTO JOB (JOB_NAME) VALUES ('매니저');

INSERT INTO AGENCY (NAME, PHONE, ADDRESS) VALUES ('강남점', '0211112222', '서울특별시 강남구 테헤란로 14길 6');
INSERT INTO AGENCY (NAME, PHONE, ADDRESS) VALUES ('서초점', '0222223333', '서울특별시 서초구 서초대로 77');
INSERT INTO AGENCY (NAME, PHONE, ADDRESS) VALUES ('송파점', '0233334444', '서울특별시 송파구 올림픽로 300');
INSERT INTO AGENCY (NAME, PHONE, ADDRESS) VALUES ('마포점', '0244445555', '서울특별시 마포구 월드컵북로 21');
INSERT INTO AGENCY (NAME, PHONE, ADDRESS) VALUES ('영등포점', '0255556666', '서울특별시 영등포구 여의대로 12');

INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (1, 'admin01', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '김국비', '01012345678', '서울특별시 강남구', '테헤란로 14길 6 남도빌딩 5층', 'admin01@test.com', 1, '9612231234567', 3500000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (1, 'employee01', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '안국비', '01012348756', '서울특별시 강남구', '테헤란로 14길 6 남도빌딩 2층', 'employee01@test.com', 4, '9611131234567', 2200000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (2, 'manager02', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '박서초', '01022223333', '서울특별시 서초구', '서초대로 77 3층', 'manager02@test.com', 2, '9001011234567', 3000000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (2, 'employee02', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '최서초', '01023456789', '서울특별시 서초구', '서초대로 77 2층', 'employee02@test.com', 4, '9505051234567', 2100000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (3, 'manager03', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '이송파', '01034567890', '서울특별시 송파구', '올림픽로 300 4층', 'manager03@test.com', 2, '9207071234567', 3000000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (3, 'employee03', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '정송파', '01045678901', '서울특별시 송파구', '올림픽로 300 2층', 'employee03@test.com', 3, '9808081234567', 2400000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (4, 'manager04', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '한마포', '01056789012', '서울특별시 마포구', '월드컵북로 21 5층', 'manager04@test.com', 2, '9309091234567', 3000000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (4, 'employee04', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '오마포', '01067890123', '서울특별시 마포구', '월드컵북로 21 2층', 'employee04@test.com', 4, '9901012234567', 2100000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (5, 'manager05', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '윤영등포', '01078901234', '서울특별시 영등포구', '여의대로 12 6층', 'manager05@test.com', 2, '9403031234567', 3000000);
INSERT INTO EMPLOYEE (AGENCY_NO, ID, PW, NAME, PHONE, ADDRESS, ADDRESS2, EMAIL, JOB_NO, RESIDENT, SALARY) VALUES (5, 'employee05', '$2a$10$EVZuU.GSGNsps.cMe3eA0eH/A0WsNX3AdqiBk7qKXQ4KSvIImCNE6', '임영등포', '01089012345', '서울특별시 영등포구', '여의대로 12 3층', 'employee05@test.com', 5, '9704041234567', 2300000);

UPDATE AGENCY SET MANAGER_NO = 1 WHERE NO = 1;
UPDATE AGENCY SET MANAGER_NO = 3 WHERE NO = 2;
UPDATE AGENCY SET MANAGER_NO = 5 WHERE NO = 3;
UPDATE AGENCY SET MANAGER_NO = 7 WHERE NO = 4;
UPDATE AGENCY SET MANAGER_NO = 9 WHERE NO = 5;

INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('5G 요금제 이용 중 LTE로 변경 가능한가요?', '네, 위약금 발생 여부 확인 후 변경 가능합니다. 단, 공시지원금 수혜 시 유지 기간을 확인해 주세요.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('남은 데이터를 다음 달로 이월할 수 있나요?', '데이터 이월 서비스가 포함된 전용 요금제를 이용하시는 경우에만 다음 달까지 이월이 가능합니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('청소년 요금제는 만 몇 세까지 이용 가능한가요?', '만 18세 이하 고객님까지 가입 가능하며, 만 19세 생일이 되는 다음 달 1일에 일반 요금제로 자동 전환됩니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('실버 요금제 가입 자격이 어떻게 되나요?', '만 65세 이상의 고객님이라면 가입 가능합니다. 기초연금 수급자일 경우 추가 감면 혜택이 있습니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('가족 결합 할인 혜택은 얼마나 되나요?', '결합 인원 및 요금제 구간에 따라 월 최대 50%까지 할인 혜택을 받으실 수 있습니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('군인 전용 요금제 가입 시 필요한 서류는?', '입영통지서, 현역 복무 확인서 등 군 복무 중임을 증명할 수 있는 서류가 필요합니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('무제한 요금제인데 속도 제한(QoS)이 있나요?', '기본 제공량 소진 후 요금제별로 정해진 속도(1Mbps~5Mbps)로 데이터 이용이 가능합니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('기초생활수급자 요금 감면 신청은 어떻게 하나요?', '신분증을 지참하여 대리점에 방문하시거나 정부24 사이트를 통해 비대면 신청이 가능합니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('데이터 쉐어링 서비스 이용료는 얼마인가요?', '요금제에 따라 1~2회선까지 무료인 경우가 많으며, 추가 시 회선당 월 8,250원이 부과됩니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('외국인도 요금제 가입이 가능한가요?', '외국인 등록증 또는 거소 신고증을 소지한 경우 가입 가능합니다.', '요금제문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('선택약정할인과 공시지원금의 차이는 무엇인가요?', '공시지원금은 기기값 할인, 선택약정은 매달 통신요금의 25%를 할인받는 방식입니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('약정 기간 중 해지하면 위약금이 얼마인가요?', '남은 약정 기간과 사용한 할인 혜택에 따라 계산 방식이 상이하므로 고객센터 확인이 필요합니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('재약정은 언제부터 신청할 수 있나요?', '기존 약정 만료 180일 전부터 재약정 신청 및 혜택 승계가 가능합니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('군 입대 시 약정 정지가 가능한가요?', '군 입대 장기 일시정지를 신청하시면 약정 기간 진행이 멈추며 위약금이 청구되지 않습니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('기기변경 시 위약금이 면제되는 조건은?', '동일 통신사 유지 및 특정 약정 기간 경과(보통 18개월 이상) 시 위약금이 유예될 수 있습니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('선택약정 1년과 2년의 할인율 차이가 있나요?', '할인율은 25%로 동일합니다. 다만 약정 기간 설정에 따른 위약금 구조가 다릅니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('할부금 완납은 어디서 하나요?', '대리점 방문, 고객센터 전화, 홈페이지를 통해 즉시 완납이 가능합니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('명의 변경 시 약정도 승계되나요?', '양도인과 양수인 합의 하에 약정 및 잔여 할부금 승계가 가능합니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('약정이 종료되면 자동으로 연장되나요?', '자동 연장되지 않습니다. 종료 전 문자를 안내드리며 별도로 재약정을 신청하셔야 합니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('해지 시 할부금이 남아있으면 어떻게 되나요?', '남은 기기 할부금은 매달 청구되거나 즉시 일시불로 납부하셔야 합니다.', '약정문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('번호이동(통신사 변경) 시 주의사항은?', '현재 결합 할인 해지 여부와 미납 요금, 위약금 발생 여부를 미리 확인해 주세요.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('일시정지 신청은 1년에 몇 번 가능한가요?', '연간 최대 2회, 총합 180일까지 신청 가능합니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('해외 로밍 신청은 어떻게 하나요?', '출국 전 앱 또는 공항 내 로밍 센터에서 신청하시거나, 해외 도착 후 문자로 신청 가능합니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('분실 신고 후 핸드폰 위치 찾기가 가능한가요?', '분실 신고 시 위치 추적 서비스를 신청하시면 최종 위치를 안내받으실 수 있습니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('번호 변경은 온라인으로 가능한가요?', '홈페이지나 앱의 [마이페이지 > 번호변경] 메뉴에서 90일에 2회까지 가능합니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('명의 도용 방지 서비스는 무엇인가요?', '본인 명의로 신규 회선이 개통되지 않도록 사전에 차단하는 서비스입니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('유심(USIM) 재발급 비용은 얼마인가요?', '나노 유심 기준 7,700원이 발생하며 익월 요금에 합산 청구됩니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('미납 요금이 있을 때 발신 정지는 언제 되나요?', '납기일로부터 보통 1개월 경과 시 발신이 정지되며, 이후 수신도 정지됩니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('통화 품질 불만 시 방문 점검 요청이 가능한가요?', '네, 고객센터를 통해 접수하시면 엔지니어가 직접 방문하여 수신 환경을 체크합니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('법인 명의 가입 시 필요 서류는?', '사업자등록증 사본, 법인 인감증명서, 대리인 신분증 등이 필요합니다.', '서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('컬러링(통화 연결음) 설정은 어떻게 하나요?', '전용 앱이나 홈페이지를 통해 음원을 구매하여 설정하실 수 있습니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('스팸 차단 서비스는 유료인가요?', '기본 스팸 차단 서비스는 무료로 제공되며, 강력한 차단을 원하시면 유료 서비스를 신청하세요.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('유튜브 프리미엄 제휴 혜택이 있나요?', '특정 고가 요금제 이용 시 유튜브 프리미엄 구독료를 할인하거나 지원해 드립니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('단말기 파손 보험 가입 기간은 언제까지인가요?', '신규 개통 또는 기기변경 후 30일 이내에만 가입 가능합니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('데이터 안심옵션 서비스가 무엇인가요?', '기본 데이터 소진 후 추가 요금 없이 낮은 속도로 데이터를 계속 쓰는 서비스입니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('투넘버 서비스는 어떻게 쓰나요?', '하나의 폰에서 두 개의 번호를 이용하는 서비스로 월 3,300원의 이용료가 발생합니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('클라우드 서비스 연동은 어떻게 하나요?', '통신사 전용 클라우드 앱을 설치하고 본인인증을 통해 연동 가능합니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('부가서비스 해지는 당일 취소가 되나요?', '가입 후 1시간 이내에만 당일 취소가 가능하며, 이후에는 일할 계산되어 청구됩니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('로밍 에그(Egg) 대여는 어디서 하나요?', '공항 로밍 센터에서 출국 전 대여 및 입국 후 반납이 가능합니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('OTT(넷플릭스 등) 결합 상품 신청 방법은?', '고객센터나 앱의 부가서비스 탭에서 결합형 상품을 선택하여 가입하실 수 있습니다.', '부가서비스문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('가까운 직영 대리점 위치는 어디서 보나요?', '홈페이지의 [매장 찾기] 메뉴에서 위치 및 영업시간 확인이 가능합니다.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('대리점 방문 시 예약이 필요한가요?', '예약 없이 방문 가능하나, 네이버 예약을 통해 대기 시간을 줄이실 수 있습니다.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('대리점에서 중고폰 보상 판매도 하나요?', '네, 민팃(MINTIT) 등 제휴된 보상 기기를 통해 중고폰 즉시 매입 서비스를 제공합니다.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('주말에도 대리점이 영업하나요?', '대부분의 대리점이 토요일은 운영하나, 일요일은 지점별로 상이하므로 미리 확인해 주세요.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('대리점에서 요금 수납 시 카드 결제 가능한가요?', '네, 본인 명의 카드로 당월 및 미납 요금 수납이 모두 가능합니다.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('가족이 대신 업무를 보려면 무엇을 가져가야 하나요?', '명의자 신분증, 방문자 신분증, 가족관계증명서가 필요합니다.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('대리점과 직영점의 차이가 무엇인가요?', '직영점은 본사가 직접 운영하여 모든 CS 업무가 가능하며, 대리점은 개통 위주로 운영됩니다.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('분실된 핸드폰 임대폰 대여가 가능한가요?', '가까운 직영 매장을 방문하시면 잔여 재고 확인 후 임대폰 대여를 도와드립니다.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('대리점에서 키즈폰 체험이 가능한가요?', '주요 매장에는 키즈 체험존이 마련되어 있어 아이와 함께 체험해 보실 수 있습니다.', '대리점문의', 1);
INSERT INTO FAQ (QUESTION, ANSWER, CATEGORY, WRITER_NO) VALUES ('개통한 지 얼마 안 되었는데 대리점에서 교환 가능한가요?', '기기 결함일 경우 서비스센터 판정서 지참 시 개통 14일 이내 교환 가능합니다.', '대리점문의', 1);

INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[공지] 차세대 6G 네트워크망 고도화 작업에 따른 일시 점검 안내', '안녕하세요. 고객님께 더 나은 품질을 제공하기 위해 망 고도화 작업을 진행합니다. 점검 시간 동안 일부 지역에서 데이터 속도 저하가 발생할 수 있으니 양해 부탁드립니다. 점검 일시: 2026-04-10 02:00 ~ 05:00', 452, SYSDATE - 10);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[약관] 개인정보 처리방침 개정 및 시행 안내 (2026년 5월)', '개인정보 보호법 개정에 따라 당사의 개인정보 처리방침이 변경될 예정입니다. 변경된 주요 내용은 제3자 제공 동의 항목의 구체화이며, 상세 내용은 첨부파일을 확인해 주시기 바랍니다.', 1205, SYSDATE - 8);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[이벤트] 봄맞이 가족결합 고객 대상 OTT 3개월 무료 이용권 증정', '따뜻한 봄을 맞아 가족 결합 상품을 이용 중인 고객님들께 넷플릭스 또는 디즈니+ 3개월 무료 이용권을 드립니다. 지금 바로 이벤트 페이지에서 신청하세요!', 3210, SYSDATE - 7);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[안내] 삼성 갤럭시 S27 시리즈 사전 예약 및 혜택 안내', '가장 진화한 인공지능 스마트폰, 갤럭시 S27 시리즈의 사전 예약이 시작됩니다. 사전 예약 고객님께는 단말기 10% 즉시 할인과 전용 정품 케이스를 증정합니다.', 5600, SYSDATE - 6);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[시스템] 멤버십 포인트 소멸 예정 및 사용 권장 안내', '2025년도에 적립된 멤버십 포인트가 이번 달 말일자로 소멸될 예정입니다. 제휴처 및 온라인 쇼핑몰에서 남은 포인트를 알뜰하게 사용하시기 바랍니다.', 890, SYSDATE - 5);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[보안] 통신사 사칭 스팸/피싱 문자 주의 안내', '최근 당사를 사칭하여 "미납 요금이 있으니 링크를 클릭하라"는 문자가 기승을 부리고 있습니다. 당사는 절대로 문자 내 링크를 통한 앱 설치를 요구하지 않습니다.', 2400, SYSDATE - 4);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[신규서비스] 1인가구 전용 저가형 다이렉트 요금제 출시 안내', '오직 온라인에서만 가입 가능한 초저가 다이렉트 요금제가 출시되었습니다. 약정 없이 자유롭게, 필요한 만큼만 결제하는 스마트한 통신 생활을 시작해 보세요.', 1560, SYSDATE - 3);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[안내] 구글 플레이 스토어 결제 방식 변경 및 수수료 정책 안내', '콘텐츠 이용료 결제 시 적용되는 구글의 정책 변경으로 인해 결제 한도 및 방식이 일부 변경되었습니다. 이용에 불편함이 없도록 상세 페이지를 확인 바랍니다.', 670, SYSDATE - 2);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[보도] 당사 고객 만족도 조사(NCSI) 15년 연속 1위 달성 기념', '고객 여러분의 성원 덕분에 국가 고객 만족도 조사에서 15년 연속 1위를 달성했습니다. 감사의 마음을 담아 모든 고객님께 이번 달 데이터 10GB를 추가 제공합니다.', 4100, SYSDATE - 1);
INSERT INTO NOTICE (WRITER_NO, TITLE, CONTENT, HIT, CREATED_AT) VALUES (1, '[긴급] Apple iOS 19 업데이트 이후 통화 수신 끊김 현상 해결 방법', '최신 iOS 업데이트 이후 일부 기기에서 발생하는 통화 끊김 현상에 대한 임시 해결 방법을 안내드립니다. 설정 -> 네트워크 초기화 후 재부팅을 권장합니다.', 7800, SYSDATE);

INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '요금제 상담 요청', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '부가서비스 문의', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '해지 관련 상담', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '요금제 변경 문의', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '결제 오류 상담', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '데이터 무제한 문의', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '로밍 서비스 상담', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '요금제 추천 요청', 5);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '번호 변경 문의', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '인터넷 속도 문의', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '요금 할인 문의', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '결제 수단 변경 요청', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '약정 기간 문의', 5);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '유심 교체 상담', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '명의 변경 문의', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '통화 품질 문제', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '문자 수신 오류', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '데이터 끊김 현상', 5);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '요금 과다 청구 문의', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '서비스 해지 요청', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '요금제 업그레이드', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '할인 혜택 문의', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '가입 조건 문의', 5);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '추가 요금 발생 문의', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '번호 이동 상담', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '데이터 추가 구매', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '속도 제한 문의', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '해외 사용 가능 여부', 5);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '부가서비스 해지', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '자동이체 오류', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '요금 납부 확인', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '계정 정보 변경', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '앱 로그인 오류', 5);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '이벤트 문의', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '고객센터 연결 요청', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '요금제 해지 조건', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '데이터 공유 문의', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '신규 가입 상담', 5);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '기기 변경 문의', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '유심 등록 오류', 2);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (1, '요금 청구서 문의', 3);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (2, '번호 정지 해제 요청', 4);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (3, '서비스 이용 불가', 5);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (4, '약정 해지 문의', 1);
INSERT INTO COUNSEL (MEMBER_NO, CONTENT, WRITER_NO) VALUES (5, '부가서비스 추천', 2);

BEGIN
  FOR i IN 2..21 LOOP
    INSERT INTO ACCOUNT (
        NO,
        ACCOUNT_NUMBER,
        PAYMENT_NO
    ) VALUES (
        SEQ_ACCOUNT.NEXTVAL,
        '1234' || LPAD(i, 12, '0'),
        FLOOR(DBMS_RANDOM.VALUE(1, 41))
    );
  END LOOP;
  COMMIT;
END;
/

DECLARE
    TYPE num_tab IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;
    v_mem_nos num_tab;
    v_plan_nos num_tab;
    v_contract_nos num_tab;
    
    v_line_count NUMBER;
    v_phone_suffix NUMBER := 1000;
    
    v_selected_plan_no NUMBER;
    v_selected_contract_no NUMBER;
BEGIN
    SELECT NO BULK COLLECT INTO v_mem_nos FROM (SELECT NO FROM MEMBER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 15;
    SELECT NO BULK COLLECT INTO v_plan_nos FROM PLAN;
    SELECT NO BULK COLLECT INTO v_contract_nos FROM MAIN_CONTRACT;

    FOR i IN 1..v_mem_nos.COUNT LOOP
        v_line_count := FLOOR(DBMS_RANDOM.VALUE(1, 4)); 

        FOR j IN 1..v_line_count LOOP
            v_phone_suffix := v_phone_suffix + 1;
            
            v_selected_plan_no := v_plan_nos(FLOOR(DBMS_RANDOM.VALUE(1, v_plan_nos.COUNT + 1)));
            v_selected_contract_no := v_contract_nos(FLOOR(DBMS_RANDOM.VALUE(1, v_contract_nos.COUNT + 1)));
            
            INSERT INTO ACCOUNT (NO, ACCOUNT_NUMBER, PAYMENT_NO)
            VALUES (SEQ_ACCOUNT.NEXTVAL, '9876' || LPAD(v_mem_nos(i), 8, '0') || LPAD(j, 4, '0'), FLOOR(DBMS_RANDOM.VALUE(1, 41)));

            INSERT INTO FIXED_INFO (
                NO,
                MEMBER_NO,
                PHONE,
                CREATED_AT,
                MAIN_CONTRACT_END_DATE,
                ACCOUNT_NO,
                MAIN_CONTRACT_NO,
                PLAN_NO,
                ACTIVE_YN
            ) VALUES (
                SEQ_FIXED_INFO.NEXTVAL,
                v_mem_nos(i),
                '010' || '9999' || LPAD(v_phone_suffix, 4, '0'), 
                SYSDATE - FLOOR(DBMS_RANDOM.VALUE(1, 365)),
                TO_CHAR(ADD_MONTHS(SYSDATE, FLOOR(DBMS_RANDOM.VALUE(6, 36))), 'YYYYMMDD'),
                SEQ_ACCOUNT.CURRVAL,
                v_selected_contract_no,
                v_selected_plan_no,
                CASE WHEN DBMS_RANDOM.VALUE < 0.7 THEN 'Y' ELSE 'N' END
            );
        END LOOP;
    END LOOP;
    COMMIT;
END;
/

DECLARE
    TYPE num_tab IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;
    v_fixed_nos num_tab;
    TYPE month_tab IS TABLE OF VARCHAR2(6);
    v_months month_tab := month_tab(
        '202511', '202512', '202601', '202602', '202603'
    );
    v_inserted_count NUMBER := 0;
BEGIN
    SELECT NO BULK COLLECT INTO v_fixed_nos FROM FIXED_INFO;
    FOR i IN 1..v_fixed_nos.COUNT LOOP
        FOR m IN 1..v_months.COUNT LOOP
            INSERT INTO PLAN_CONTRACT (
                NO,
                FIXED_NO,
                USED_DATA,
                USED_VOICE,
                USED_SMS,
                USED_MONTH,
                PERSONAL_PLAN_NO
            ) VALUES (
                SEQ_PLAN_CONTRACT.NEXTVAL,
                v_fixed_nos(i),
                FLOOR(DBMS_RANDOM.VALUE(2000, 60001)), 
                FLOOR(DBMS_RANDOM.VALUE(30, 501)),    
                FLOOR(DBMS_RANDOM.VALUE(10, 201)),    
                v_months(m),
                (SELECT PLAN_NO FROM FIXED_INFO WHERE NO = v_fixed_nos(i))
            );
            v_inserted_count := v_inserted_count + 1;
        END LOOP;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('25년 11월 ~ 26년 3월 데이터 ' || v_inserted_count || '건 생성 완료!');
END;
/

DECLARE
    CURSOR c_fixed IS
        SELECT 
            NO AS fixed_no, 
            PLAN_NO
        FROM FIXED_INFO;
    v_month VARCHAR2(6);
    v_usage_data NUMBER;
BEGIN
    FOR rec IN c_fixed LOOP
        FOR m IN 1..3 LOOP
            v_month := '2026' || LPAD(m, 2, '0');
            v_usage_data := FLOOR(DBMS_RANDOM.VALUE(1024, 20480));
            INSERT INTO PLAN_CONTRACT (
                NO,
                FIXED_NO,
                USED_DATA,
                USED_VOICE,
                USED_SMS,
                USED_MONTH,
                PERSONAL_PLAN_NO
            ) VALUES (
                SEQ_PLAN_CONTRACT.NEXTVAL,
                rec.fixed_no,
                v_usage_data,
                FLOOR(DBMS_RANDOM.VALUE(10, 200)),
                FLOOR(DBMS_RANDOM.VALUE(0, 50)),
                v_month,
                rec.PLAN_NO
            );
        END LOOP;
    END LOOP;
    COMMIT;
END;
/

DECLARE
    V_MAX_ROWS NUMBER := 100;
BEGIN
    INSERT INTO SERVICE_INSERT_CONFIRM (
        NO, 
        EMPLOYEE_NO, 
        SERVICE_NO, 
        FIXED_NO, 
        CONFIRM_AT, 
        CONFIRM_STATUS
    )
    WITH RAW_DATA AS (
        SELECT 
            F_NO, 
            S_NO,
            ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE) as RN
        FROM (SELECT LEVEL F_NO FROM DUAL CONNECT BY LEVEL <= 20)
        CROSS JOIN (SELECT LEVEL S_NO FROM DUAL CONNECT BY LEVEL <= 30)
    )
    SELECT 
        SEQ_SERVICE_INSERT_CONFIRM.NEXTVAL,
        CASE 
            WHEN STATUS_SEED < 0.3 THEN NULL
            ELSE TRUNC(DBMS_RANDOM.VALUE(1, 3))
        END as EMPLOYEE_NO,
        S_NO as SERVICE_NO,
        F_NO as FIXED_NO,
        CASE 
            WHEN STATUS_SEED < 0.3 THEN NULL
            ELSE SYSDATE - DBMS_RANDOM.VALUE(0, 30)
        END as CONFIRM_AT,
        CASE 
            WHEN STATUS_SEED < 0.3 THEN 'A'
            WHEN STATUS_SEED < 0.7 THEN 'Y'
            ELSE 'N'
        END as CONFIRM_STATUS
    FROM (
        SELECT F_NO, S_NO, DBMS_RANDOM.VALUE as STATUS_SEED
        FROM RAW_DATA
        WHERE RN <= V_MAX_ROWS
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE(V_MAX_ROWS || ' rows inserted into SERVICE_INSERT_CONFIRM.');
END;
/

DECLARE
    TYPE VARCHAR_TAB IS TABLE OF VARCHAR2(100);
    V_TITLES VARCHAR_TAB := VARCHAR_TAB(
        '요금제 변경 문의드립니다.', '데이터 로밍 관련 질문', '약정 만료일 확인 부탁해요', 
        '결합 할인 혜택이 안 들어온 것 같아요', '핸드폰 분실 신고 접수', '유심 인식 불량', 
        '멤버십 등급 확인', '미납 요금 납부 방법', '소액결제 차단 신청', '번호 이동 절차'
    );
    
    V_CONTENTS VARCHAR_TAB := VARCHAR_TAB(
        '상세한 내용을 알고 싶습니다. 연락 주세요.', '홈페이지에서 확인이 어려워 글 남깁니다.', 
        '최대한 빨리 처리 부탁드립니다.', '갑자기 서비스가 안 되어서 당황스럽네요.', 
        '증빙 서류는 어떤 게 필요한가요?', '가족 결합 관련해서 궁금한 게 많습니다.',
        '이전 상담원분이 안내해주신 내용과 다릅니다.', '금액이 생각보다 많이 나왔어요.'
    );

    V_CATEGORIES VARCHAR_TAB := VARCHAR_TAB('요금제', '단말기', '결합상품', '로밍', '기타');
    
    V_SEL_TITLE    VARCHAR2(100);
    V_SEL_CONTENT  VARCHAR2(4000);
    V_SEL_CATEGORY VARCHAR2(100);
    V_COUNT        NUMBER; 
BEGIN
    FOR i IN 1..50 LOOP
        V_COUNT := TRUNC(DBMS_RANDOM.VALUE(0, 4)); 
        
        IF V_COUNT > 0 THEN
            FOR j IN 1..V_COUNT LOOP
                V_SEL_TITLE    := V_TITLES(TRUNC(DBMS_RANDOM.VALUE(1, V_TITLES.COUNT + 1)));
                V_SEL_CONTENT  := V_CONTENTS(TRUNC(DBMS_RANDOM.VALUE(1, V_CONTENTS.COUNT + 1)));
                V_SEL_CATEGORY := V_CATEGORIES(TRUNC(DBMS_RANDOM.VALUE(1, V_CATEGORIES.COUNT + 1)));

                INSERT INTO QA (
                    TITLE, 
                    CONTENT, 
                    CATEGORY, 
                    WRITER_NO, 
                    CREATED_AT
                ) VALUES (
                    V_SEL_TITLE,
                    V_SEL_CONTENT,
                    V_SEL_CATEGORY,
                    i, 
                    SYSDATE - DBMS_RANDOM.VALUE(0, 60)
                );
            END LOOP;
        END IF;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('QA dummy data generation completed.');
END;
/
DECLARE
    V_PENALTY_COUNT NUMBER := 0;
    V_EXTRA_COUNT   NUMBER := TRUNC(DBMS_RANDOM.VALUE(1, 3)); -- 1~2건
    V_FEE           NUMBER;
BEGIN
    INSERT INTO BILLING (
        NO,
        FIXED_NO,
        PLAN_CONTRACT_NO,
        BILL_MONTH,
        BILL_TOTAL,
        ETC_BIL,
        PAY_YN
    )
    SELECT 
        SEQ_BILLING.NEXTVAL,
        FIXED_NO,
        NO,
        USED_MONTH,
        0,
        0,
        CASE WHEN DBMS_RANDOM.VALUE < 0.5 THEN 'Y' ELSE 'N' END
    FROM (
        SELECT 
            PC.*,
            ROW_NUMBER() OVER (PARTITION BY FIXED_NO, USED_MONTH ORDER BY NO) RN
        FROM PLAN_CONTRACT PC
    )
    WHERE RN = 1;

    -- 기존: 위약금 3건
    FOR rec IN (
        SELECT NO FROM (
            SELECT NO FROM BILLING ORDER BY DBMS_RANDOM.VALUE
        ) WHERE ROWNUM <= 3
    ) LOOP
        V_FEE := TRUNC(DBMS_RANDOM.VALUE(10000, 50000), -2);

        UPDATE BILLING 
        SET ETC_BIL = V_FEE,
            BILL_TOTAL = BILL_TOTAL + V_FEE
        WHERE NO = rec.NO;
    END LOOP;

    -- 추가: 1~2건 약 10000원
    FOR rec IN (
        SELECT NO FROM (
            SELECT NO FROM BILLING 
            WHERE ETC_BIL = 0   -- 이미 선택된 것 제외
            ORDER BY DBMS_RANDOM.VALUE
        ) WHERE ROWNUM <= V_EXTRA_COUNT
    ) LOOP
        V_FEE := TRUNC(DBMS_RANDOM.VALUE(9000, 11000), -2); -- 약 10000

        UPDATE BILLING 
        SET ETC_BIL = V_FEE,
            BILL_TOTAL = BILL_TOTAL + V_FEE
        WHERE NO = rec.NO;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('BILLING 생성 완료 (위약금 3건 + 소액 ' || V_EXTRA_COUNT || '건)');
END;
/


DECLARE
    V_MAX_SERVICES_PER_BILL NUMBER := 5; 
BEGIN
    DELETE FROM SERVICE_CONTRACT;

    FOR rec IN (SELECT NO, FIXED_NO, BILL_MONTH FROM BILLING) LOOP
        
        INSERT INTO SERVICE_CONTRACT (
            NO,
            FIXED_NO,
            SERVICE_NO,
            BILL_NO,
            USED_MONTH,
            DISCOUNT_RATE,
            DEL_DATE
        )
        SELECT 
            SEQ_SERVICE_CONTRACT.NEXTVAL,
            rec.FIXED_NO,
            S_NO,
            rec.NO,
            rec.BILL_MONTH,
            CASE WHEN DBMS_RANDOM.VALUE < 0.9 THEN 0 ELSE 100 END,
            CASE 
                WHEN DBMS_RANDOM.VALUE < 0.2 
                THEN TO_DATE(rec.BILL_MONTH || TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(1, 29)), 'FM00'), 'YYYYMMDD')
                ELSE NULL 
            END
        FROM (
            SELECT S_NO 
            FROM (
                SELECT LEVEL AS S_NO FROM DUAL CONNECT BY LEVEL <= 30
                MINUS
                SELECT SERVICE_NO FROM SERVICE_CONTRACT WHERE FIXED_NO = rec.FIXED_NO AND BILL_NO = rec.NO
            )
            ORDER BY DBMS_RANDOM.VALUE
        )
        WHERE ROWNUM <= TRUNC(DBMS_RANDOM.VALUE(1, V_MAX_SERVICES_PER_BILL + 1));
        
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('SERVICE_CONTRACT 대량 생성이 완료되었습니다. (건당 최대 5개 서비스)');
END;
/

DECLARE
    V_MAX_ROWS NUMBER := 30; 
BEGIN
    INSERT INTO SERVICE_DELETE_CONFIRM (
        NO, 
        EMPLOYEE_NO, 
        SERVICE_CONTRACT_NO, 
        FIXED_NO,
        CONFIRM_AT, 
        CONFIRM_STATUS
    )
    WITH RAW_DATA AS (
        SELECT 
            NO AS SC_NO,
            FIXED_NO AS F_NO,
            DEL_DATE AS SC_DEL_DATE,
            ROW_NUMBER() OVER (ORDER BY DBMS_RANDOM.VALUE) as RN
        FROM SERVICE_CONTRACT
        WHERE DEL_DATE IS NOT NULL 
    )
    SELECT 
        SEQ_SERVICE_DELETE_CONFIRM.NEXTVAL,
        CASE 
            WHEN STATUS_SEED < 0.2 THEN NULL 
            ELSE TRUNC(DBMS_RANDOM.VALUE(1, 3)) 
        END,
        SC_NO, 
        F_NO,
        CASE 
            WHEN STATUS_SEED < 0.2 THEN NULL 
            ELSE SC_DEL_DATE + DBMS_RANDOM.VALUE(0, 3) 
        END,
        CASE 
            WHEN STATUS_SEED < 0.2 THEN 'A'
            WHEN STATUS_SEED < 0.8 THEN 'Y'
            ELSE 'N'
        END
    FROM (
        SELECT SC_NO, F_NO, SC_DEL_DATE, DBMS_RANDOM.VALUE as STATUS_SEED
        FROM RAW_DATA
        WHERE RN <= V_MAX_ROWS 
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' rows inserted into SERVICE_DELETE_CONFIRM.');
END;
/

INSERT INTO PLAN_INSERT_CONFIRM (NO, EMPLOYEE_NO, FIXED_NO, CONFIRM_AT, CONFIRM_STATUS)
SELECT 
    SEQ_PLAN_INSERT_CONFIRM.NEXTVAL,
    CASE WHEN LEVEL <= 25 THEN MOD(LEVEL, 2) + 1 ELSE NULL END,
    MOD(LEVEL, 10) + 1,
    CASE WHEN LEVEL <= 25 THEN SYSDATE - (LEVEL/24) ELSE NULL END,
    CASE 
        WHEN LEVEL <= 25 THEN (CASE WHEN MOD(LEVEL, 10) = 0 THEN 'N' ELSE 'Y' END)
        ELSE 'A' 
    END
FROM DUAL CONNECT BY LEVEL <= 30;

INSERT INTO PLAN_UPDATE_CONFIRM (NO, EMPLOYEE_NO, FIXED_NO, NEW_PLAN_NO, CONFIRM_AT, CONFIRM_STATUS)
SELECT 
    SEQ_PLAN_UPDATE_CONFIRM.NEXTVAL,
    CASE WHEN LEVEL <= 20 THEN MOD(LEVEL, 2) + 1 ELSE NULL END,
    MOD(LEVEL, 10) + 1,
    MOD(LEVEL, 5) + 1,
    CASE WHEN LEVEL <= 20 THEN SYSDATE - MOD(LEVEL, 10) ELSE NULL END,
    CASE 
        WHEN LEVEL <= 20 THEN (CASE WHEN MOD(LEVEL, 3) = 0 THEN 'N' ELSE 'Y' END)
        ELSE 'A' 
    END
FROM DUAL CONNECT BY LEVEL <= 30;

INSERT INTO PLAN_DELETE_CONFIRM (NO, EMPLOYEE_NO, FIXED_NO, CONFIRM_AT, CONFIRM_STATUS)
SELECT 
    SEQ_PLAN_DELETE_CONFIRM.NEXTVAL,
    CASE WHEN LEVEL <= 15 THEN MOD(LEVEL, 2) + 1 ELSE NULL END,
    MOD(LEVEL, 10) + 1,
    CASE WHEN LEVEL <= 15 THEN SYSDATE - (LEVEL/5) ELSE NULL END,
    CASE 
        WHEN LEVEL <= 15 THEN (CASE WHEN MOD(LEVEL, 5) = 0 THEN 'N' ELSE 'Y' END)
        ELSE 'A' 
    END
FROM DUAL CONNECT BY LEVEL <= 30;



COMMIT;