--------------------------------------------------
-- 시퀀스 삭제
--------------------------------------------------
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_REPLY;
DROP SEQUENCE SEQ_GALLERY;
DROP SEQUENCE SEQ_GALLERY_ATTACHMENT;
DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_HOBBY;

--------------------------------------------------
-- 테이블 삭제
--------------------------------------------------
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE GALLERY CASCADE CONSTRAINTS;
DROP TABLE GALLERY_ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD_LIKE CASCADE CONSTRAINTS;
DROP TABLE HOBBY CASCADE CONSTRAINTS;

--------------------------------------------------
-- 시퀀스 생성
--------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_REPLY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GALLERY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GALLERY_ATTACHMENT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HOBBY NOCYCLE;

--------------------------------------------------
-- 테이블 생성
--------------------------------------------------
CREATE TABLE MEMBER(
    NO                      NUMBER          DEFAULT SEQ_MEMBER.NEXTVAL CONSTRAINT MEMBER_PK PRIMARY KEY
    ,ID                     VARCHAR2(100)   CONSTRAINT MEMBER_ID_NN NOT NULL CONSTRAINT MEMBER_ID_UQ UNIQUE
    ,PW                     VARCHAR2(100)   CONSTRAINT MEMBER_PW_NN NOT NULL
    ,NICK                   VARCHAR2(100)   CONSTRAINT MEMBER_NICK_NN NOT NULL CONSTRAINT MEMBER_NICK_UQ UNIQUE
    ,HOBBY                  VARCHAR2(100)   
    ,PROFILE_CHANGE_NAME    VARCHAR2(1000)
    ,PROFILE_ORIGIN_NAME    VARCHAR2(1000)
    ,CREATED_AT             TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP       
    ,QUIT_YN                CHAR(1)         DEFAULT 'N' CONSTRAINT MEMBER_QUIT_YN_CK CHECK( QUIT_YN IN ('Y','N') )
);

CREATE TABLE BOARD(
    NO              NUMBER          DEFAULT SEQ_BOARD.NEXTVAL CONSTRAINT BOARD_PK PRIMARY KEY
    ,TITLE          VARCHAR2(100)   CONSTRAINT BOARD_TITLE_NN NOT NULL
    ,CONTENT        VARCHAR2(4000)  CONSTRAINT BOARD_CONTENT_NN NOT NULL
    ,WRITER_NO      NUMBER          CONSTRAINT BOARD_FK REFERENCES MEMBER(NO)
    ,HIT            NUMBER          DEFAULT 0 CONSTRAINT BOARD_HIT_CK CHECK(HIT >= 0)
    ,CREATED_AT     TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT     TIMESTAMP       
    ,DEL_YN         CHAR(1)         DEFAULT 'N' CONSTRAINT BOARD_DEL_YN_CK CHECK( DEL_YN IN ('Y', 'N') )
);

CREATE TABLE BOARD_REPLY(
    NO          NUMBER          DEFAULT SEQ_BOARD_REPLY.NEXTVAL CONSTRAINT BOARD_REPLY_PK PRIMARY KEY
    ,CONTENT    VARCHAR2(300)   CONSTRAINT BOARD_REPLY_CONTENT_NN NOT NULL
    ,BOARD_NO   NUMBER          CONSTRAINT BOARD_REPLY_BNO_NN NOT NULL
    ,WRITER_NO  NUMBER          CONSTRAINT BOARD_REPLY_WNO_NN NOT NULL
    ,CREATED_AT TIMESTAMP       DEFAULT SYSDATE
    ,DEL_YN     CHAR(1)         DEFAULT 'N' CONSTRAINT BOARD_REPLY_DEL_CK CHECK (DEL_YN IN ('Y','N'))
);

CREATE TABLE GALLERY(
    NO          NUMBER          DEFAULT SEQ_GALLERY.NEXTVAL CONSTRAINT GALLERY_PK PRIMARY KEY
    ,TITLE      VARCHAR2(1000)  CONSTRAINT GALLERY_TITLE_NN NOT NULL
    ,WRITER_NO  NUMBER          CONSTRAINT GALLERY_WNO_NN NOT NULL
    ,HIT        NUMBER          DEFAULT 0
    ,CREATED_AT TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT TIMESTAMP       
    ,DEL_YN     CHAR(1)         DEFAULT 'N' CONSTRAINT GALLERY_DEL_CK CHECK (DEL_YN IN ('Y','N'))
);

CREATE TABLE GALLERY_ATTACHMENT(
    NO              NUMBER          DEFAULT SEQ_GALLERY_ATTACHMENT.NEXTVAL CONSTRAINT GALLERY_ATTACH_PK PRIMARY KEY
    ,GALLERY_NO     NUMBER          CONSTRAINT GALLERY_ATTCH_NO_NN NOT NULL
    ,CHANGE_NAME    VARCHAR2(1000)  CONSTRAINT GALLERY_ATTACH_CNAME_NN NOT NULL
    ,ORIGIN_NAME    VARCHAR2(1000)  CONSTRAINT GALLERY_ATTACH_ONAME_NN NOT NULL
    ,THUMBNAIL_YN   CHAR(1)         DEFAULT 'N' CONSTRAINT GALLERY__ATTACH_TUMB_CK CHECK (THUMBNAIL_YN IN ('Y','N'))
);

CREATE TABLE ADMIN(
    NO          NUMBER          DEFAULT SEQ_ADMIN.NEXTVAL CONSTRAINT ADMIN_PK PRIMARY KEY
    ,ID         VARCHAR2(30)    CONSTRAINT ADMIN_ID_NN NOT NULL CONSTRAINT ADMIN_ID_UQ UNIQUE
    ,PW         VARCHAR2(100)   CONSTRAINT ADMIN_PW_NN NOT NULL
    ,NICK       VARCHAR2(30)    CONSTRAINT ADMIN_NICK_NN NOT NULL CONSTRAINT ADMIN_NICK_UQ UNIQUE
    ,CREATED_AT TIMESTAMP       DEFAULT SYSDATE
    ,DEL_YN     CHAR(1)         DEFAULT 'N' CONSTRAINT ADMIN_DEL_CK CHECK (DEL_YN IN ('Y','N'))
);

CREATE TABLE NOTICE(
    NO          NUMBER          DEFAULT SEQ_NOTICE.NEXTVAL CONSTRAINT NOTICE_PK PRIMARY KEY
    ,TITLE      VARCHAR2(1000)  CONSTRAINT NOTICE_TITLE_NN NOT NULL
    ,CONTENT    VARCHAR2(4000)  CONSTRAINT NOTICE_CONTENT_NN NOT NULL
    ,WRITER_NO  NUMBER          CONSTRAINT NOTICE_WNO_NN NOT NULL
    ,HIT        NUMBER          DEFAULT 0
    ,CREATED_AT TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT TIMESTAMP       
    ,DEL_YN     CHAR(1)         DEFAULT 'N' CONSTRAINT NOTICE_DEL_CK CHECK (DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_LIKE(
    MEMBER_NO   NUMBER
    , BOARD_NO  NUMBER
    , CONSTRAINT BOARD_LIKE_PK PRIMARY KEY (MEMBER_NO, BOARD_NO)
);

CREATE TABLE HOBBY(
    NO      NUMBER          DEFAULT SEQ_HOBBY.NEXTVAL CONSTRAINT HOBBY_PK PRIMARY KEY
    , NAME  VARCHAR2(100)   CONSTRAINT HOBBY_NAME_NN NOT NULL
);


--------------------------------------------------
-- 외래키 연결
--------------------------------------------------
ALTER TABLE BOARD_REPLY
ADD 
(
CONSTRAINT BOARD_REPLY_BNO_FK FOREIGN KEY (BOARD_NO) REFERENCES BOARD (NO)
, CONSTRAINT BOARD_REPLY_WNO_FK FOREIGN KEY (WRITER_NO) REFERENCES MEMBER (NO)
)
;

ALTER TABLE GALLERY
ADD 
CONSTRAINT GALLERY_WNO_FK FOREIGN KEY (WRITER_NO) REFERENCES MEMBER (NO)
;

ALTER TABLE GALLERY_ATTACHMENT
ADD 
CONSTRAINT GALLERY_ATTACH_FK FOREIGN KEY (GALLERY_NO) REFERENCES GALLERY (NO)
;

ALTER TABLE NOTICE
ADD 
CONSTRAINT NOTICE_FK FOREIGN KEY (WRITER_NO) REFERENCES ADMIN (NO)
;

ALTER TABLE BOARD_LIKE
ADD 
(
CONSTRAINT BOARD_LIKE_MNO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO)
, CONSTRAINT BOARD_LIKE_BNO_FK FOREIGN KEY (BOARD_NO) REFERENCES BOARD(NO)
)
;

--------------------------------------------------
-- 더미데이터 준비
--------------------------------------------------
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '수영');
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '낚시');
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '등산');
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '코딩');
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '댄스');
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '요리');
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '게임');
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '명상');
INSERT INTO HOBBY (NO , NAME) VALUES(SEQ_HOBBY.NEXTVAL , '운동');
COMMIT;

INSERT INTO MEMBER(ID,PW,NICK,HOBBY) VALUES('user01' , '$2a$10$4gvqBrjwkw7jOjvfZAX/SujhPN27Ru1TL6djGKnAGs08HKGICHcrG', 'nick01' , '1,2,3');
INSERT INTO MEMBER(ID,PW,NICK,HOBBY) VALUES('user02' , '$2a$10$4gvqBrjwkw7jOjvfZAX/SujhPN27Ru1TL6djGKnAGs08HKGICHcrG', 'nick02' , '4,5,6');
INSERT INTO MEMBER(ID,PW,NICK,HOBBY) VALUES('user03' , '$2a$10$4gvqBrjwkw7jOjvfZAX/SujhPN27Ru1TL6djGKnAGs08HKGICHcrG', 'nick03' , '7,8,9');
COMMIT;

INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목01' , '내용01' , 1);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목02' , '내용02' , 1);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목03' , '내용03' , 1);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목04' , '내용04' , 1);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목05' , '내용05' , 1);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목06' , '내용06' , 2);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목07' , '내용07' , 2);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목08' , '내용08' , 2);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목09' , '내용09' , 2);
INSERT INTO BOARD(TITLE, CONTENT, WRITER_NO) VALUES('제목10' , '내용10' , 2);
COMMIT;
