
DROP SEQUENCE SEQ_NOTICE;
CREATE SEQUENCE SEQ_NOTICE NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_QA;
CREATE SEQUENCE SEQ_QA NOCACHE NOCYCLE;

DROP SEQUENCE NOTICE_FILE;
CREATE SEQUENCE NOTICE_FILE NOCACHE NOCYCLE;

DROP SEQUENCE REPLY;
CREATE SEQUENCE REPLY NOCACHE NOCYCLE;

DROP SEQUENCE FAQ;
CREATE SEQUENCE FAQ NOCACHE NOCYCLE;

DROP SEQUENCE QA_FILE;
CREATE SEQUENCE QA_FILE NOCACHE NOCYCLE;


DROP TABLE NOTICE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE (
	NO	        NUMBER	        DEFAULT SEQ_NOTICE.NEXTVAL  CONSTRAINT NOTICE_NO_PK PRIMARY KEY,
	WRITER_NO	NUMBER	        CONSTRAINT NOTICE_FK        REFERENCES EMPLOYEE(NO),
	TITLE	    VARCHAR2(100)	CONSTRAINT NOTICE_TITLE_NN  NOT NULL,
	CONTENT	    VARCHAR2(4000)	CONSTRAINT NOTICE_NO_NN     NOT NULL,
	HIT	        NUMBER		    DEFAULT 0   CONSTRAINT NOTICE_HIT_CK CHECK(HIT >= 0),
	CREATED_AT	TIMESTAMP	    DEFAULT SYSDATE,
	UPDATED_AT	TIMESTAMP	    DEFAULT SYSDATE,
	DEL_YN	    CHAR(1)	        DEFAULT 'N' CHECK( DEL_YN IN ('Y', 'N'))
);

DROP TABLE QA CASCADE CONSTRAINTS;
CREATE TABLE QA (
	NO	        NUMBER	        DEFAULT SEQ_QA.NEXTVAL,
	TITLE	    VARCHAR2(100)	NOT NULL,
	CONTENT	    VARCHAR2(4000)	NOT NULL,
	CREATED_AT	TIMESTAMP	    DEFAULT SYSDATE,
	UPDATED_AT	TIMESTAMP	    DEFAULT SYSDATE,
	WRITER_NO	NUMBER	        NOT NULL,
	REPLY_YN	CHAR(1)	        DEFAULT 'N' CHECK( DEL_YN IN ('Y', 'N') )
);

DROP TABLE NOTICE_FILE CASCADE CONSTRAINTS;
CREATE TABLE NOTICE_FILE (
	NO	        NUMBER	NULL	DEFAULT SEQ_NOTICE_FILE.NEXTVAL,
	NAME	    VARCHAR2(1000)	NOT NULL,
	URL	        VARCHAR2(4000)	NOT NULL,
	ORIGIN_NAME	VARCHAR2(100)	NULL,
	NOTICE_NO	NUMBER	NULL	DEFAULT SEQ_NOTICE.NEXTVAL
);

DROP TABLE REPLY CASCADE CONSTRAINTS;
CREATE TABLE REPLY (
	NO	        NUMBER	NULL	DEFAULT SEQ_REPLY.NEXTVAL,
	CONTENT	    VARCHAR2(1000)	NULL,
	CREATED_AT	TIMESTAMP	NOT NULL	DEFAULT SYSDATE,
	EMPLOYEE_NO	NUMBER	NOT NULL	DEFAULT SEQ_EMPLOYEE,
	QA_NO	    NUMBER	NOT NULL	DEFAULT SEQ_QA_BOARD.NEXTVAL	COMMENT 'PK'
);

DROP TABLE FAQ CASCADE CONSTRAINTS;
CREATE TABLE FAQ (
	NO	        NUMBER	NOT NULL	DEFAULT SEQ_FAQ.NEXTVAL	COMMENT 'PK',
	QUESTION	VARCHAR2(100)	NOT NULL,
	ANSWER	    VARCHAR2(4000)	NOT NULL,
	HIT	        NUMBER	NOT NULL	DEFAULT 0,
	WRITER_NO	NUMBER	NOT NULL	COMMENT 'REFERENCES EMPLOYEE(NO)'
);

DROP TABLE QA_FILE CASCADE CONSTRAINTS;
CREATE TABLE QA_FILE (
	NO	        NUMBER	NULL	DEFAULT SEQ_QA_FILE.NEXTVAL,
	NAME	    VARCHAR2(1000)	NOT NULL,
	URL	        VARCHAR2(4000)	NOT NULL,
	ORIGIN_NAME	VARCHAR2(100)	NULL,
	QA_NO	    NUMBER	NOT NULL	DEFAULT SEQ_QA_BOARD.NEXTVAL	COMMENT 'PK'
);
