

--------------------------------------------------
-- 시퀀스 삭제
--------------------------------------------------
DROP SEQUENCE SEQ_MAIN_CONTRACT ;
DROP SEQUENCE SEQ_PAYMENT ;
DROP SEQUENCE SEQ_PLAN ;
DROP SEQUENCE SEQ_DATA_SPEED ;
DROP SEQUENCE SEQ_ADD_SERVICE ;
DROP SEQUENCE SEQ_EMPLOYEE;
DROP SEQUENCE SEQ_COUNSEL;
DROP SEQUENCE SEQ_JOB;
DROP SEQUENCE SEQ_AGENCY;
DROP SEQUENCE SEQ_QA;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_QA_FILE;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_NOTICE_FILE;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_BILLING;
DROP SEQUENCE SEQ_SERVICE_CONTRACT;
DROP SEQUENCE SEQ_SERVICE_DELETE_CONFIRM;
DROP SEQUENCE SEQ_SERVICE_INSERT_CONFIRM;
DROP SEQUENCE SEQ_PLAN_CONTRACT;
DROP SEQUENCE SEQ_FIXED_INFO;
DROP SEQUENCE SEQ_ACCOUNT;
DROP SEQUENCE SEQ_PLAN_UPDATE_CONFIRM;
DROP SEQUENCE SEQ_PLAN_DELETE_CONFIRM;
DROP SEQUENCE SEQ_PLAN_INSERT_CONFIRM;
DROP SEQUENCE SEQ_MEMBER;
--------------------------------------------------
-- 테이블 삭제
--------------------------------------------------
DROP TABLE MAIN_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE PLAN CASCADE CONSTRAINTS;
DROP TABLE DATA_SPEED CASCADE CONSTRAINTS;
DROP TABLE ADD_SERVICE CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE COUNSEL CASCADE CONSTRAINTS;
DROP TABLE JOB CASCADE CONSTRAINTS;
DROP TABLE AGENCY CASCADE CONSTRAINTS;
DROP TABLE QA CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE QA_FILE CASCADE CONSTRAINTS;
DROP TABLE FAQ  CASCADE CONSTRAINTS;
DROP TABLE NOTICE_FILE CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE BILLING CASCADE CONSTRAINTS;
DROP TABLE SERVICE_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE SERVICE_DELETE_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE SERVICE_INSERT_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE PLAN_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE FIXED_INFO CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE PLAN_UPDATE_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE PLAN_DELETE_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE PLAN_INSERT_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

--------------------------------------------------
-- 시퀀스 생성
--------------------------------------------------
CREATE SEQUENCE SEQ_MAIN_CONTRACT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAYMENT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DATA_SPEED NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADD_SERVICE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COUNSEL NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_JOB NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AGENCY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QA NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_QA_FILE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FAQ NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE_FILE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPLY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BILLING NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_CONTRACT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_DELETE_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_INSERT_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_CONTRACT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FIXED_INFO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACCOUNT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_UPDATE_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_DELETE_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PLAN_INSERT_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;

--------------------------------------------------
-- 테이블 생성
--------------------------------------------------
CREATE TABLE MAIN_CONTRACT (
	NO	                          NUMBER	      DEFAULT SEQ_MAIN_CONTRACT.NEXTVAL CONSTRAINT MAIN_CONTRACT_PK PRIMARY KEY
	, TERM                        VARCHAR2(10)    DEFAULT '12' CONSTRAINT MAIN_CONTRACT_CK CHECK(TERM IN ('12','24','36'))
    , DISCOUNT_RATE               NUMBER          DEFAULT 25
    , PENALTY                     NUMBER          DEFAULT 0
);

CREATE TABLE DATA_SPEED (
	NO	            NUMBER	            DEFAULT SEQ_DATA_SPEED.NEXTVAL CONSTRAINT DATA_SPEED_PK PRIMARY KEY
	 ,SPEED	        VARCHAR2(100)	    CONSTRAINT DATA_SPEED_SPEED_NN NOT NULL
	 ,DONE_SPEED	VARCHAR2(100)	    CONSTRAINT DATA_SPEED_DONE_NN NOT NULL
);

CREATE TABLE PLAN (
	NO	                NUMBER		        DEFAULT SEQ_PLAN.NEXTVAL CONSTRAINT PLAN_PK PRIMARY KEY
	 ,NAME	            VARCHAR2(100)	    CONSTRAINT PLAN_NAME_NN NOT NULL CONSTRAINT PLAN_UQ UNIQUE	
	 ,PRICE	            NUMBER	            CONSTRAINT PLAN_PRICE_NN NOT NULL 
	 ,DATA_TOTAL	    VARCHAR2(100)         CONSTRAINT PLAN_DATA_NN NOT NULL
	 ,VOICE_TOTAL	    VARCHAR2(100)	            CONSTRAINT PLAN_VOICE_NN NOT NULL
	 ,SMS_TOTAL	        VARCHAR2(100)	            CONSTRAINT PLAN_SMS_NN NOT NULL
	 ,SELL_YN	        CHAR(1)	            DEFAULT 'Y'	CONSTRAINT PLAN_YN_CK CHECK( SELL_YN IN ('Y','N'))
	 ,DATA_NO	        NUMBER	            CONSTRAINT PLAN_DATA_NO_NN NOT NULL 
     ,DATA_SHARE        VARCHAR2(100)       CONSTRAINT PLAN_DATA_SHARE_NN NOT NULL
     ,CATEGORY          VARCHAR2(100)       
     ,DESCRIPTION       VARCHAR2(4000) 
);




CREATE TABLE PAYMENT (
	NO	            NUMBER	            DEFAULT SEQ_PAYMENT.NEXTVAL CONSTRAINT PAYMENT_PK PRIMARY KEY
	, NAME	        VARCHAR2(100)	    CONSTRAINT PAYMENT_NAME_NN NOT NULL CONSTRAINT PAYMENT_NAME_UQ UNIQUE 
);

CREATE TABLE ADD_SERVICE(
    NO              NUMBER              DEFAULT SEQ_ADD_SERVICE.NEXTVAL CONSTRAINT ADD_SERVICE_PK PRIMARY KEY  
    , SERVICE       VARCHAR2(300)       CONSTRAINT ADD_SERVICE_SERVICE_NN NOT NULL
    , CONTENT       VARCHAR2(1000)      CONSTRAINT ADD_SERVICE_CONTENT_NN NOT NULL
    , PRICE         NUMBER              DEFAULT 10000
    , SELL_YN       CHAR(1)             DEFAULT 'Y'	CONSTRAINT ADD_SERVICE_YN_CK CHECK( SELL_YN IN ('Y','N'))
    , CREATED_AT    TIMESTAMP           DEFAULT SYSDATE
    , CATEGORY      VARCHAR2(100)       CONSTRAINT ADD_SERVICE_CK CHECK( CATEGORY IN ('DATA','OTT','SECURITY','INSURANCE','ROAMING'))
    
);
CREATE TABLE EMPLOYEE(
    NO                      NUMBER          DEFAULT SEQ_EMPLOYEE.NEXTVAL CONSTRAINT MEMBER_PK PRIMARY KEY
    ,AGENCY_NO              NUMBER          CONSTRAINT EMPLOYEE_AGENCY_NO_NN NOT NULL
    ,ID                     VARCHAR2(100)   CONSTRAINT EMPLOYEE_ID_NN NOT NULL CONSTRAINT EMPLOYEE_ID_UQ UNIQUE
    ,PW                     VARCHAR2(100)   CONSTRAINT EMPLOYEE_PW_NN NOT NULL
    ,NAME                   VARCHAR2(100)   CONSTRAINT EMPLOYEE_NAME_NN NOT NULL
    ,PHONE                  CHAR(11)        CONSTRAINT EMPLOYEE_PHONE_NN NOT NULL
    ,ADDRESS                VARCHAR2(100)   CONSTRAINT EMPLOYEE_ADDRESS_NN NOT NULL
    ,ADDRESS2                VARCHAR2(100)   CONSTRAINT EMPLOYEE_ADDRESS2_NN NOT NULL
    ,EMAIL                  VARCHAR2(100)   CONSTRAINT EMPLOYEE_EMAIL_NN NOT NULL
    ,JOB_NO                 NUMBER          DEFAULT 1 CONSTRAINT EMPLOYEE_JOB_NO_NN NOT NULL
    ,RESIDENT               CHAR(13)        CONSTRAINT EMPLOYEE_RESIDENT_NN NOT NULL
    ,SALARY                 NUMBER          DEFAULT 2000000 CONSTRAINT EMPLOYEE_SALARY_NN NOT NULL
    ,CREATED_AT             TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP       
    ,QUIT_YN                CHAR(1)         DEFAULT 'N' CONSTRAINT EMPLOYEE_QUIT_YN_CK CHECK( QUIT_YN IN ('Y','N') )
    ,PROFILE_CHANGE_NAME    VARCHAR2(1000)
    ,PROFILE_ORIGIN_NAME    VARCHAR2(1000)
);

CREATE TABLE COUNSEL(
    NO              NUMBER          DEFAULT SEQ_COUNSEL.NEXTVAL CONSTRAINT COUNSEL_PK PRIMARY KEY
    ,MEMBER_NO      NUMBER          CONSTRAINT COUNSEL_MEMBER_NO_NN NOT NULL
    ,COUNSEL_DATE   TIMESTAMP       DEFAULT SYSDATE
    ,CONTENT        VARCHAR2(4000)  CONSTRAINT COUNSEL_CONTENT_NN NOT NULL
    ,WRITER_NO      NUMBER          CONSTRAINT COUNSEL_WRITER_NO_NN NOT NULL
    
);

CREATE TABLE JOB(
    NO              NUMBER          DEFAULT SEQ_JOB.NEXTVAL CONSTRAINT JOB_PK PRIMARY KEY
    ,JOB_NAME       VARCHAR2(100)   CONSTRAINT JOB_JOB_NAME_NN NOT NULL CONSTRAINT JOB_JOB_NAME_UQ UNIQUE
);

CREATE TABLE AGENCY(
    NO                      NUMBER          DEFAULT SEQ_AGENCY.NEXTVAL CONSTRAINT AGENCY_PK PRIMARY KEY
    ,MANAGER_NO             NUMBER          
    ,NAME                   VARCHAR2(100)   CONSTRAINT AGENCY_NAME_NN NOT NULL
    ,PHONE                  CHAR(11)        CONSTRAINT AGENCY_PHONE_NN NOT NULL
    ,ADDRESS                VARCHAR2(100)   CONSTRAINT AGENCY_ADDRESS_NN NOT NULL
    ,CREATED_AT             TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP       
    ,QUIT_YN                CHAR(1)         DEFAULT 'N' CONSTRAINT AGENCY_QUIT_YN_CK CHECK( QUIT_YN IN ('Y','N') )
);

CREATE TABLE QA(
    NO                      NUMBER            DEFAULT SEQ_QA.NEXTVAL CONSTRAINT QA_PK PRIMARY KEY   
    ,TITLE                  VARCHAR2(100)     CONSTRAINT QA_TITLE_NN NOT NULL 
    ,CONTENT                VARCHAR2(4000)    CONSTRAINT QA_CONTENT_NN NOT NULL 
    ,CATEGORY               VARCHAR2(100)     CONSTRAINT QA_CATEGORY_NN NOT NULL
    ,CREATED_AT             TIMESTAMP         DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP         
    ,WRITER_NO              NUMBER            CONSTRAINT QA_WRITER_NO_NN NOT NULL  
    ,DEL_YN                 CHAR(1)           DEFAULT 'N' CONSTRAINT QA_DEL_YN_CK CHECK( DEL_YN IN ('Y','N') )
    );

CREATE TABLE NOTICE(
    NO                      NUMBER          DEFAULT SEQ_NOTICE.NEXTVAL CONSTRAINT NOTICE_PK PRIMARY KEY   
    ,WRITER_NO              NUMBER          CONSTRAINT NOTICE_WRITER_NO_NN NOT NULL 
    ,TITLE                  VARCHAR2(100)   CONSTRAINT NOTICE_TITLE_NN NOT NULL
    ,CONTENT                VARCHAR2(4000)  CONSTRAINT NOTICE_CONTENT_NN NOT NULL
    ,HIT                    NUMBER          DEFAULT 0
    ,CREATED_AT             TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT             TIMESTAMP       
    ,DEL_YN                 CHAR(1)         DEFAULT 'N' CONSTRAINT NOTICE_DEL_YN_CK CHECK( DEL_YN IN ('Y','N') )
);

CREATE TABLE FAQ(
    NO                NUMBER          DEFAULT SEQ_FAQ.NEXTVAL CONSTRAINT FAQ_PK PRIMARY KEY
    ,QUESTION         VARCHAR2(100)   CONSTRAINT FAQ_QUESTION_NN NOT NULL
    ,ANSWER           VARCHAR2(4000)  CONSTRAINT FAQ_ANSWER_NN NOT NULL
    ,WRITER_NO        NUMBER          CONSTRAINT FAQ_WRITER_NO_NN NOT NULL
    ,CREATED_AT       TIMESTAMP       DEFAULT SYSDATE
    ,UPDATED_AT       TIMESTAMP 
    ,DEL_YN           CHAR(1)         DEFAULT 'N' CONSTRAINT FAQ_DEL_YN_CK CHECK( DEL_YN IN ('Y','N') )
   
);
---------------------------------------------------------
CREATE TABLE QA_FILE(
    NO               NUMBER            DEFAULT SEQ_QA_FILE.NEXTVAL CONSTRAINT QA_FILE_PK PRIMARY KEY
  ,NAME              VARCHAR2(1000)    CONSTRAINT QA_FILE_NAME_NN NOT NULL 
  ,URL               VARCHAR2(4000)    CONSTRAINT QA_FILE_URL_NN NOT NULL
  ,ORIGIN_NAME       VARCHAR2(100)     CONSTRAINT QA_FILE_ORIGIN_NAME_NN NOT NULL 
  ,QA_NO             NUMBER            CONSTRAINT QA_FILE_QA_NO_NN NOT NULL
  );
  
  CREATE TABLE NOTICE_FILE(
    NO              NUMBER            DEFAULT SEQ_NOTICE_FILE.NEXTVAL CONSTRAINT NOTICE_FILE_PK PRIMARY KEY
    ,NAME           VARCHAR2(1000)    CONSTRAINT NOTICE_FILE_NAME_NN NOT NULL
    ,URL            VARCHAR2(4000)    CONSTRAINT NOTICE_FILE_URL_NN NOT NULL
    ,ORIGIN_NAME    VARCHAR2(100)     CONSTRAINT NOTICE_FILE_ORIGIN_NAME_NN NOT NULL  
    ,NOTICE_NO      NUMBER            CONSTRAINT NOTICE_FILE_NOTICE_NO_NN NOT NULL
);

CREATE TABLE REPLY(
    NO            NUMBER            DEFAULT SEQ_REPLY.NEXTVAL CONSTRAINT ADMIN_PK PRIMARY KEY
    ,CONTENT      VARCHAR2(1000)    CONSTRAINT REPLY_CONTENT_NN NOT NULL   
    ,CREATED_AT   TIMESTAMP         DEFAULT SYSDATE
    ,EMPLOYEE_NO  NUMBER            CONSTRAINT REPLY_EMPLOYEE_NO_NN NOT NULL
    ,QA_NO        NUMBER            CONSTRAINT REPLY_QA_NO_NN NOT NULL
);

CREATE TABLE BILLING (
	NO	                NUMBER	        DEFAULT SEQ_BILLING.NEXTVAL	CONSTRAINT BILLING_PK PRIMARY KEY
	,FIXED_NO	        NUMBER          CONSTRAINT BILLING_FIXED_NO_NN NOT NULL
	,PLAN_CONTRACT_NO   NUMBER          CONSTRAINT BILLING_PLAN_CONTRACT_NO_NN NOT NULL
	,BILL_MONTH	        VARCHAR2(6)	    CONSTRAINT BILL_MONTH_NN NOT NULL
	,BILL_TOTAL	        NUMBER	        DEFAULT 0
    ,ETC_BIL            NUMBER          DEFAULT 0
	,PAY_YN	            CHAR(1)	        DEFAULT 'N' CONSTRAINT BILL_PAY_YN_CK 	CHECK(PAY_YN IN ('Y', 'N'))
);

CREATE TABLE SERVICE_CONTRACT (
	NO	            NUMBER	        DEFAULT SEQ_SERVICE_CONTRACT.NEXTVAL CONSTRAINT SERVICE_CONTRACT_PK PRIMARY KEY
	,FIXED_NO	    NUMBER          CONSTRAINT SERVICE_CONTRACT_FIXED_NO_NN NOT NULL
	,SERVICE_NO	    NUMBER          CONSTRAINT SERVICE_CONTRACT_SERVICE_NO_NN NOT NULL
    ,BILL_NO	    NUMBER          
	,DEL_DATE	    TIMESTAMP       
	,USED_MONTH	    VARCHAR2(6)	DEFAULT TO_CHAR(SYSDATE, 'YYYYMM')
	,DISCOUNT_RATE	NUMBER	        DEFAULT 0
);

CREATE TABLE SERVICE_DELETE_CONFIRM(
    NO                      NUMBER      DEFAULT SEQ_SERVICE_DELETE_CONFIRM.NEXTVAL CONSTRAINT SERVICE_DELETE_CONFIRM_PK PRIMARY KEY
    ,EMPLOYEE_NO            NUMBER      
    ,SERVICE_CONTRACT_NO    NUMBER      CONSTRAINT SERVICE_DELETE_CONFIRM_SERVICE_CONTRACT_NO_NN NOT NULL 
    ,FIXED_NO               NUMBER      CONSTRAINT SERVICE_DELETE_CONFIRM_FIXED_NO_NN NOT NULL
    ,CONFIRM_AT             TIMESTAMP
    ,CONFIRM_STATUS         CHAR(1)     DEFAULT 'A' CONSTRAINT SERVICE_DELETE_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);

CREATE TABLE SERVICE_INSERT_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_SERVICE_INSERT_CONFIRM.NEXTVAL CONSTRAINT SERVICE_INSERT_CONFIRM_PK PRIMARY KEY
    ,EMPLOYEE_NO        NUMBER      
    ,SERVICE_NO         NUMBER      CONSTRAINT SERVICE_INSERT_CONFIRM_SERVICE_NO_NN NOT NULL 
    ,FIXED_NO           NUMBER      CONSTRAINT SERVICE_INSERT_CONFIRM_FIXED_NO_NN NOT NULL
    ,CONFIRM_AT         TIMESTAMP
    ,CONFIRM_STATUS     CHAR(1)     DEFAULT 'A' CONSTRAINT SERVICE_INSERT_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);

CREATE TABLE PLAN_CONTRACT(
    NO                  NUMBER  DEFAULT SEQ_PLAN_CONTRACT.NEXTVAL CONSTRAINT PLAN_CONTRACT_PK PRIMARY KEY
    , FIXED_NO          NUMBER  CONSTRAINT PLAN_CONTRACT_FIXED_NO_NN NOT NULL 
    , USED_DATA         NUMBER  DEFAULT 0
    , USED_VOICE        NUMBER  DEFAULT 0
    , USED_SMS          NUMBER  DEFAULT 0
    , USED_MONTH        CHAR(6) CONSTRAINT PLAN_CONTRACT_USED_MONTH_NN NOT NULL
    , PERSONAL_PLAN_NO  NUMBER  CONSTRAINT PLAN_CONTRACT_PERSONAL_PLAN_NO_NN NOT NULL 
);

CREATE TABLE FIXED_INFO(
    NO                          NUMBER      DEFAULT SEQ_FIXED_INFO.NEXTVAL CONSTRAINT FIXED_INFO_PK PRIMARY KEY
    , MEMBER_NO                 NUMBER      CONSTRAINT FIXED_INFO_MEMBER_NO_NN NOT NULL 
    , PHONE                     CHAR(11)    CONSTRAINT FIXED_INFO_PHONE_UQ UNIQUE CONSTRAINT FIXED_INFO_PHONE_CHK CHECK (LENGTH(PHONE) = 11)
    , CREATED_AT                TIMESTAMP   DEFAULT SYSDATE
    , DEL_AT                    TIMESTAMP
    , MAIN_CONTRACT_END_DATE    CHAR(8)     CONSTRAINT FIXED_INFO_MAIN_CONTRACT_END_DATE_CHK CHECK (LENGTH(MAIN_CONTRACT_END_DATE) = 8)
    , ACCOUNT_NO                NUMBER      CONSTRAINT FIXED_INFO_ACCOUNT_NO_NN NOT NULL 
    , MAIN_CONTRACT_NO          NUMBER      CONSTRAINT FIXED_INFO_MAIN_CONTRACT_NO_NN NOT NULL 
		, PLAN_NO                   NUMBER      CONSTRAINT FIXED_INFO_PLAN_NO_NN NOT NULL 
    , ACTIVE_YN                 CHAR(1)     DEFAULT 'N'	CONSTRAINT FIXED_INFO_ACTIVE_YN_NN NOT NULL CONSTRAINT FIXED_INFO_ACTIVE_YN_CK CHECK(ACTIVE_YN IN('Y','N'))
);
CREATE TABLE ACCOUNT(
    NO                  NUMBER  DEFAULT SEQ_ACCOUNT.NEXTVAL CONSTRAINT ACCOUNT_PK PRIMARY KEY
    , ACCOUNT_NUMBER    NUMBER  CONSTRAINT ACCOUNT_NUMBER_NO_NN NOT NULL 
    , PAYMENT_NO        NUMBER  CONSTRAINT ACCOUNT_PAYMENT_NO_NN NOT NULL 
);
CREATE TABLE PLAN_UPDATE_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_PLAN_UPDATE_CONFIRM.NEXTVAL CONSTRAINT PLAN_UPDATE_CONFIRM_PK PRIMARY KEY
    , EMPLOYEE_NO       NUMBER      
    , FIXED_NO          NUMBER      CONSTRAINT PLAN_UPDATE_CONFIRM_FIXED_NO_NN NOT NULL 
    , NEW_PLAN_NO       NUMBER      CONSTRAINT PLAN_UPDATE_CONFIRM_NEW_PLAN_NO_NN NOT NULL 
    , CONFIRM_AT        TIMESTAMP
    , CONFIRM_STATUS    CHAR(1)     DEFAULT 'A' CONSTRAINT PLAN_UPDATE_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);
CREATE TABLE PLAN_DELETE_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_PLAN_DELETE_CONFIRM.NEXTVAL CONSTRAINT PLAN_DELETE_CONFIRM_PK PRIMARY KEY
    , EMPLOYEE_NO       NUMBER      
    , FIXED_NO          NUMBER      CONSTRAINT PLAN_DELETE_CONFIRM_PLAN_CONTRACT_NO_NN NOT NULL 
    , CONFIRM_AT        TIMESTAMP
    , CONFIRM_STATUS    CHAR(1)     DEFAULT 'A' CONSTRAINT PLAN_DELETE_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);
CREATE TABLE PLAN_INSERT_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_PLAN_INSERT_CONFIRM.NEXTVAL CONSTRAINT PLAN_INSERT_CONFIRM_PK PRIMARY KEY
    , EMPLOYEE_NO       NUMBER      
    , FIXED_NO          NUMBER      CONSTRAINT PLAN_INSERT_CONFIRM_PLAN_CONTRACT_NO_NN NOT NULL 
    , CONFIRM_AT        TIMESTAMP
    , CONFIRM_STATUS    CHAR(1)     DEFAULT 'A' CONSTRAINT PLAN_INSERT_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);
CREATE TABLE MEMBER (
	NO	        NUMBER	            DEFAULT SEQ_MEMBER.NEXTVAL	PRIMARY KEY,
	ID	        VARCHAR2(100)		CONSTRAINT MEMBER_ID_NN NOT NULL CONSTRAINT MEMBER_ID_UQ UNIQUE,
	PW	        VARCHAR2(100)		CONSTRAINT MEMBER_PW_NN NOT NULL,
	NAME    	VARCHAR2(100)		CONSTRAINT MEMBER_NAME_NN NOT NULL,
	PHONE	    CHAR(11)		    CONSTRAINT MEMBER_PHONE_NN NOT NULL CONSTRAINT MEMBER_PHONE_UQ UNIQUE,
	ADDRESS 	VARCHAR2(100)	    CONSTRAINT MEMBER_ADDRESS_NN NOT NULL,
	ADDRESS2 	VARCHAR2(100)	    CONSTRAINT MEMBER_ADDRESS2_NN NOT NULL,
	EMAIL	    VARCHAR2(100)		CONSTRAINT MEMBER_EMAIL_NN NOT NULL CONSTRAINT MEMBER_EMAIL_UQ UNIQUE,
	RESIDENT	CHAR(13)		    CONSTRAINT MEMBER_RESIDENT_NN NOT NULL CONSTRAINT MEMBER_RESIDENT_UQ UNIQUE,
	CHANGE_NAME	VARCHAR2(1000)		,
	ORIGIN_NAME	VARCHAR2(1000)		,
	CREATED_AT	TIMESTAMP	        DEFAULT SYSDATE	CONSTRAINT MEMBER_CREATED_AT_NN NOT NULL,
	UPDATED_AT	TIMESTAMP	        ,
	QUIT_YN	    CHAR(1)	            DEFAULT 'N'	CONSTRAINT MEMBER_QUIT_YN_NN NOT NULL CONSTRAINT MEMBER_QUIT_YN_CK CHECK(QUIT_YN IN('Y','N'))
);


--------------------------------------------------
-- 외래키 연결
--------------------------------------------------
ALTER TABLE EMPLOYEE
ADD 
(
CONSTRAINT EMPLOYEE_ANO_FK FOREIGN KEY (AGENCY_NO) REFERENCES AGENCY (NO)
, CONSTRAINT EMPLOYEE_JNO_FK FOREIGN KEY (JOB_NO) REFERENCES JOB (NO)
)
;
ALTER TABLE COUNSEL
ADD 
CONSTRAINT COUNSEL_MNO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO)
;
ALTER TABLE AGENCY
ADD 
CONSTRAINT AGENCY_MNO_FK FOREIGN KEY (MANAGER_NO) REFERENCES EMPLOYEE(NO)
;

ALTER TABLE PLAN
ADD 
CONSTRAINT PLAN_DATA_NO_FK   FOREIGN KEY (DATA_NO)   REFERENCES DATA_SPEED(NO)
;

ALTER TABLE QA
ADD 
CONSTRAINT QA_WNO_FK FOREIGN KEY (WRITER_NO) REFERENCES MEMBER (NO)
;

ALTER TABLE NOTICE
ADD 
CONSTRAINT NOTICE_WNO_FK FOREIGN KEY (WRITER_NO) REFERENCES EMPLOYEE (NO)
;
ALTER TABLE FAQ
ADD
CONSTRAINT FAQ_WNO_FK FOREIGN KEY (WRITER_NO) REFERENCES EMPLOYEE (NO)
;
ALTER TABLE QA_FILE
ADD
CONSTRAINT QA_FILE_QNO_FK FOREIGN KEY (QA_NO) REFERENCES QA(NO)
;
ALTER TABLE NOTICE_FILE
ADD
CONSTRAINT NOTICE_FILE_NNO_FK FOREIGN KEY (NOTICE_NO) REFERENCES NOTICE(NO)
;
ALTER TABLE REPLY
ADD
(
CONSTRAINT REPLY_ENO_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE (NO)
,CONSTRAINT REPLY_QNO_FK FOREIGN KEY (QA_NO) REFERENCES QA (NO)
)
;
ALTER TABLE BILLING 
ADD (
CONSTRAINT BILLING_FIXED_NO_FK             FOREIGN KEY (FIXED_NO)         REFERENCES FIXED_INFO (NO)
, CONSTRAINT BILLING_PLAN_CONTRACT_NO_FK    FOREIGN KEY (PLAN_CONTRACT_NO)  REFERENCES PLAN_CONTRACT (NO)
);

ALTER TABLE SERVICE_CONTRACT
ADD (
CONSTRAINT SERVICE_CONTRACT_FIXED_NO_FK     FOREIGN KEY (FIXED_NO)     REFERENCES FIXED_INFO (NO)
, CONSTRAINT SERVICE_CONTRACT_SERVICE_NO_FK  FOREIGN KEY (SERVICE_NO)    REFERENCES ADD_SERVICE (NO)
, CONSTRAINT SERVICE_CONTRACT_BILL_NO_FK     FOREIGN KEY (BILL_NO)       REFERENCES BILLING (NO)
);

ALTER TABLE SERVICE_DELETE_CONFIRM
ADD 
(
CONSTRAINT SERVICE_DELETE_CONFIRM_EMPLOYEE_NO_FK            FOREIGN KEY (EMPLOYEE_NO)           REFERENCES EMPLOYEE(NO)
, CONSTRAINT SERVICE_DELETE_CONFIRM_SERVICE_CONTRACT_NO_FK  FOREIGN KEY (SERVICE_CONTRACT_NO)   REFERENCES SERVICE_CONTRACT(NO)
, CONSTRAINT SERVICE_DELETE_CONFIRM_FIXED_NO_FK        FOREIGN KEY (FIXED_NO)         REFERENCES FIXED_INFO(NO)
);

ALTER TABLE SERVICE_INSERT_CONFIRM
ADD 
(
CONSTRAINT SERVICE_INSERT_CONFIRM_EMPLOYEE_NO_FK        FOREIGN KEY (EMPLOYEE_NO)   REFERENCES EMPLOYEE(NO)
, CONSTRAINT SERVICE_INSERT_CONFIRM_SERVICE_NO_FK       FOREIGN KEY (SERVICE_NO)    REFERENCES ADD_SERVICE(NO)
, CONSTRAINT SERVICE_INSERT_CONFIRM_FIXED_NO_FK    FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
);

ALTER TABLE PLAN_CONTRACT
ADD 
(
CONSTRAINT PLAN_CONTRACT_FIXED_NO_FK FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
, CONSTRAINT PLAN_CONTRACT_PERSONAL_PLAN_NO_FK FOREIGN KEY (PERSONAL_PLAN_NO) REFERENCES PLAN(NO)
)
;
ALTER TABLE FIXED_INFO
ADD 
(
CONSTRAINT FIXED_INFO_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(NO)
, CONSTRAINT FIXED_INFO_ACCOUNT_NO_FK FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNT(NO)
, CONSTRAINT FIXED_INFO_MAIN_CONTRACT_NO_FK FOREIGN KEY (MAIN_CONTRACT_NO) REFERENCES MAIN_CONTRACT(NO)
, CONSTRAINT FIXED_INFO_PLAN_NO_FK FOREIGN KEY (PLAN_NO) REFERENCES PLAN(NO)
)
;
ALTER TABLE ACCOUNT
ADD 
(
CONSTRAINT ACCOUNT_PAYMENT_NO_FK FOREIGN KEY (PAYMENT_NO) REFERENCES PAYMENT(NO)
)
;
ALTER TABLE PLAN_UPDATE_CONFIRM
ADD 
(
CONSTRAINT PLAN_UPDATE_CONFIRM_EMPLOYEE_NO_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE(NO)
, CONSTRAINT PLAN_UPDATE_CONFIRM_FIXED_NO_FK FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
, CONSTRAINT PLAN_UPDATE_CONFIRM_PLAN_NO_FK FOREIGN KEY (NEW_PLAN_NO) REFERENCES PLAN(NO)
)
;
ALTER TABLE PLAN_DELETE_CONFIRM
ADD 
(
CONSTRAINT PLAN_DELETE_CONFIRM_EMPLOYEE_NO_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE(NO)
, CONSTRAINT PLAN_DELETE_CONFIRM_FIXED_NO_FK FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
)
;
ALTER TABLE PLAN_INSERT_CONFIRM
ADD 
(
CONSTRAINT PLAN_INSERT_CONFIRM_EMPLOYEE_NO_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE(NO)
, CONSTRAINT PLAN_INSERT_CONFIRM_FIXED_NO_FK FOREIGN KEY (FIXED_NO) REFERENCES FIXED_INFO(NO)
)
;



COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "PLAN_DELETE_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "BILLING"."NO" IS '청구넘버';
COMMENT ON COLUMN "BILLING"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "BILLING"."PLAN_CONTRACT_NO" IS '사용내역 번호';
COMMENT ON COLUMN "BILLING"."BILL_MONTH" IS '청구월';
COMMENT ON COLUMN "BILLING"."BILL_TOTAL" IS '총청구금액';
COMMENT ON COLUMN "BILLING"."PAY_YN" IS '수납상태';
COMMENT ON COLUMN "BILLING"."ETC_BIL" IS '추가청구금액';

COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."NEW_PLAN_NO" IS '바꿀요금제번호';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "PLAN_UPDATE_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "JOB"."NO" IS '직급번호';
COMMENT ON COLUMN "JOB"."JOB_NAME" IS '직급명';

COMMENT ON COLUMN "NOTICE"."NO" IS '글 번호';
COMMENT ON COLUMN "NOTICE"."WRITER_NO" IS '작성자 번호';
COMMENT ON COLUMN "NOTICE"."TITLE" IS '제목';
COMMENT ON COLUMN "NOTICE"."CONTENT" IS '내용';
COMMENT ON COLUMN "NOTICE"."HIT" IS '조회수';
COMMENT ON COLUMN "NOTICE"."CREATED_AT" IS '작성일시';
COMMENT ON COLUMN "NOTICE"."UPDATED_AT" IS '수정일시';
COMMENT ON COLUMN "NOTICE"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "SERVICE_CONTRACT"."NO" IS '계약 번호';
COMMENT ON COLUMN "SERVICE_CONTRACT"."BILL_NO" IS '청구넘버';
COMMENT ON COLUMN "SERVICE_CONTRACT"."SERVICE_NO" IS '서비스 번호';
COMMENT ON COLUMN "SERVICE_CONTRACT"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "SERVICE_CONTRACT"."USED_MONTH" IS '사용년월';
COMMENT ON COLUMN "SERVICE_CONTRACT"."DISCOUNT_RATE" IS '할인률';
COMMENT ON COLUMN "SERVICE_CONTRACT"."DEL_DATE" IS '해지날짜';

COMMENT ON COLUMN "QA_FILE"."NO" IS '파일번호';
COMMENT ON COLUMN "QA_FILE"."NAME" IS '파일이름';
COMMENT ON COLUMN "QA_FILE"."URL" IS '파일경로';
COMMENT ON COLUMN "QA_FILE"."ORIGIN_NAME" IS '원본파일명';
COMMENT ON COLUMN "QA_FILE"."QA_NO" IS '문의번호';

COMMENT ON COLUMN "QA"."NO" IS '문의번호';
COMMENT ON COLUMN "QA"."TITLE" IS '제목';
COMMENT ON COLUMN "QA"."CONTENT" IS '내용';
COMMENT ON COLUMN "QA"."CATEGORY" IS '카테고리';
COMMENT ON COLUMN "QA"."CREATED_AT" IS '등록날짜';
COMMENT ON COLUMN "QA"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "QA"."WRITER_NO" IS '작성자번호';
COMMENT ON COLUMN "QA"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "ACCOUNT"."NO" IS '결제수단 번호';
COMMENT ON COLUMN "ACCOUNT"."ACCOUNT_NUMBER" IS '식별번호';
COMMENT ON COLUMN "ACCOUNT"."PAYMENT_NO" IS '결제사번호';

COMMENT ON COLUMN "COUNSEL"."NO" IS '상담번호';
COMMENT ON COLUMN "COUNSEL"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "COUNSEL"."CONTENT" IS '내용요약';
COMMENT ON COLUMN "COUNSEL"."COUNSEL_DATE" IS '상담날짜';
COMMENT ON COLUMN "COUNSEL"."WRITER_NO" IS '작성직원';

COMMENT ON COLUMN "MAIN_CONTRACT"."NO" IS '약정번호';
COMMENT ON COLUMN "MAIN_CONTRACT"."TERM" IS '약정기간';
COMMENT ON COLUMN "MAIN_CONTRACT"."DISCOUNT_RATE" IS '할인율';
COMMENT ON COLUMN "MAIN_CONTRACT"."PENALTY" IS '위약금비율';

COMMENT ON COLUMN "MEMBER"."NO" IS '회원번호';
COMMENT ON COLUMN "MEMBER"."ID" IS '아이디';
COMMENT ON COLUMN "MEMBER"."PW" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."NAME" IS '이름';
COMMENT ON COLUMN "MEMBER"."PHONE" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';
COMMENT ON COLUMN "MEMBER"."ADDRESS2" IS '상세주소';
COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';
COMMENT ON COLUMN "MEMBER"."RESIDENT" IS '주민등록번호';
COMMENT ON COLUMN "MEMBER"."CHANGE_NAME" IS '신분증이름';
COMMENT ON COLUMN "MEMBER"."ORIGIN_NAME" IS '신분증원본이름';
COMMENT ON COLUMN "MEMBER"."CREATED_AT" IS '가입날짜';
COMMENT ON COLUMN "MEMBER"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "MEMBER"."QUIT_YN" IS '탈퇴여부';

COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."SERVICE_CONTRACT_NO" IS '계약 번호';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "SERVICE_DELETE_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "PLAN_CONTRACT"."NO" IS '사용내역 번호';
COMMENT ON COLUMN "PLAN_CONTRACT"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "PLAN_CONTRACT"."USED_DATA" IS '사용데이터양';
COMMENT ON COLUMN "PLAN_CONTRACT"."USED_VOICE" IS '사용한전화(분)';
COMMENT ON COLUMN "PLAN_CONTRACT"."USED_SMS" IS '사용한문자횟수';
COMMENT ON COLUMN "PLAN_CONTRACT"."USED_MONTH" IS '사용년월';
COMMENT ON COLUMN "PLAN_CONTRACT"."PERSONAL_PLAN_NO" IS '요금제번호';

COMMENT ON COLUMN "DATA_SPEED"."NO" IS '속도번호';
COMMENT ON COLUMN "DATA_SPEED"."SPEED" IS '소진전 속도';
COMMENT ON COLUMN "DATA_SPEED"."DONE_SPEED" IS '소진후 속도';

COMMENT ON COLUMN "PLAN"."NO" IS '요금제번호';
COMMENT ON COLUMN "PLAN"."NAME" IS '요금제의 이름';
COMMENT ON COLUMN "PLAN"."PRICE" IS '요금제의 가격';
COMMENT ON COLUMN "PLAN"."DATA_TOTAL" IS '요금제의 종류마다 다른 총데이터양';
COMMENT ON COLUMN "PLAN"."VOICE_TOTAL" IS '기본 전화가능 시간(분)';
COMMENT ON COLUMN "PLAN"."SMS_TOTAL" IS '문자가능기본횟수';
COMMENT ON COLUMN "PLAN"."SELL_YN" IS '요금제의 판매 상황';
COMMENT ON COLUMN "PLAN"."DATA_NO" IS '속도번호';
COMMENT ON COLUMN "PLAN"."DATA_SHARE" IS '공유데이터';
COMMENT ON COLUMN "PLAN"."CATEGORY" IS '카테고리';
COMMENT ON COLUMN "PLAN"."DESCRIPTION" IS '설명';

COMMENT ON COLUMN "AGENCY"."NO" IS '대리점 넘버';
COMMENT ON COLUMN "AGENCY"."MANAGER_NO" IS '본사관리자 번호';
COMMENT ON COLUMN "AGENCY"."NAME" IS '대리점 이름';
COMMENT ON COLUMN "AGENCY"."ADDRESS" IS '주소';
COMMENT ON COLUMN "AGENCY"."PHONE" IS '연락처';
COMMENT ON COLUMN "AGENCY"."CREATED_AT" IS '등록날짜';
COMMENT ON COLUMN "AGENCY"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "AGENCY"."QUIT_YN" IS '폐점여부';

COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."SERVICE_NO" IS '서비스 번호';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "SERVICE_INSERT_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "NOTICE_FILE"."NO" IS '파일번호';
COMMENT ON COLUMN "NOTICE_FILE"."NAME" IS '파일이름';
COMMENT ON COLUMN "NOTICE_FILE"."URL" IS '파일경로';
COMMENT ON COLUMN "NOTICE_FILE"."ORIGIN_NAME" IS '원본파일명';
COMMENT ON COLUMN "NOTICE_FILE"."NOTICE_NO" IS '글 번호';

COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."NO" IS '신청번호';
COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."EMPLOYEE_NO" IS '처리직원번호';
COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."FIXED_NO" IS '가입정보 번호';
COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."CONFIRM_AT" IS '처리날짜';
COMMENT ON COLUMN "PLAN_INSERT_CONFIRM"."CONFIRM_STATUS" IS '승인여부';

COMMENT ON COLUMN "REPLY"."NO" IS '문의답글 번호';
COMMENT ON COLUMN "REPLY"."CONTENT" IS '내용';
COMMENT ON COLUMN "REPLY"."CREATED_AT" IS '등록날짜';
COMMENT ON COLUMN "REPLY"."EMPLOYEE_NO" IS '직원번호';
COMMENT ON COLUMN "REPLY"."QA_NO" IS '문의번호';

COMMENT ON COLUMN "FIXED_INFO"."NO" IS '가입정보 번호';
COMMENT ON COLUMN "FIXED_INFO"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "FIXED_INFO"."PHONE" IS '개통된 전화번호';
COMMENT ON COLUMN "FIXED_INFO"."CREATED_AT" IS '요금제 가입날짜';
COMMENT ON COLUMN "FIXED_INFO"."DEL_AT" IS '해지날짜';
COMMENT ON COLUMN "FIXED_INFO"."MAIN_CONTRACT_END_DATE" IS '약정종료날짜';
COMMENT ON COLUMN "FIXED_INFO"."ACCOUNT_NO" IS '결제수단 번호';
COMMENT ON COLUMN "FIXED_INFO"."MAIN_CONTRACT_NO" IS '약정번호';
COMMENT ON COLUMN "FIXED_INFO"."PLAN_NO" IS '요금제번호';
COMMENT ON COLUMN "FIXED_INFO"."ACTIVE_YN" IS '활성화여부';

COMMENT ON COLUMN "FAQ"."NO" IS 'PK';
COMMENT ON COLUMN "FAQ"."QUESTION" IS '질문';
COMMENT ON COLUMN "FAQ"."ANSWER" IS '답변';
COMMENT ON COLUMN "FAQ"."WRITER_NO" IS '작성자 번호';
COMMENT ON COLUMN "FAQ"."DEL_YN" IS '삭제여부';
COMMENT ON COLUMN "FAQ"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "FAQ"."CREATED_AT" IS '생성날짜';

COMMENT ON COLUMN "EMPLOYEE"."NO" IS '직원번호';
COMMENT ON COLUMN "EMPLOYEE"."AGENCY_NO" IS '대리점 넘버';
COMMENT ON COLUMN "EMPLOYEE"."ID" IS '아이디';
COMMENT ON COLUMN "EMPLOYEE"."PW" IS '비밀번호';
COMMENT ON COLUMN "EMPLOYEE"."NAME" IS '이름';
COMMENT ON COLUMN "EMPLOYEE"."PHONE" IS '전화번호';
COMMENT ON COLUMN "EMPLOYEE"."ADDRESS" IS '주소';
COMMENT ON COLUMN "EMPLOYEE"."ADDRESS2" IS '상세주소';
COMMENT ON COLUMN "EMPLOYEE"."EMAIL" IS '이메일';
COMMENT ON COLUMN "EMPLOYEE"."RESIDENT" IS '주민번호';
COMMENT ON COLUMN "EMPLOYEE"."JOB_NO" IS '직급번호';
COMMENT ON COLUMN "EMPLOYEE"."SALARY" IS '월급';
COMMENT ON COLUMN "EMPLOYEE"."CREATED_AT" IS '입사날짜';
COMMENT ON COLUMN "EMPLOYEE"."UPDATED_AT" IS '수정날짜';
COMMENT ON COLUMN "EMPLOYEE"."QUIT_YN" IS '퇴사여부';
COMMENT ON COLUMN "EMPLOYEE"."PROFILE_CHANGE_NAME" IS '프로필이름';
COMMENT ON COLUMN "EMPLOYEE"."PROFILE_ORIGIN_NAME" IS '프로필원본이름';

COMMENT ON COLUMN "ADD_SERVICE"."NO" IS '서비스 번호';
COMMENT ON COLUMN "ADD_SERVICE"."SERVICE" IS '서비스명';
COMMENT ON COLUMN "ADD_SERVICE"."CONTENT" IS '내용';
COMMENT ON COLUMN "ADD_SERVICE"."PRICE" IS '가격';
COMMENT ON COLUMN "ADD_SERVICE"."SELL_YN" IS '판매여부';
COMMENT ON COLUMN "ADD_SERVICE"."CREATED_AT" IS '생성일자';
COMMENT ON COLUMN "ADD_SERVICE"."CATEGORY" IS '카테고리';

COMMENT ON COLUMN "PAYMENT"."NO" IS '결제사 번호';
COMMENT ON COLUMN "PAYMENT"."NAME" IS '결제사 이름';