----------------------------------------------
--DROP SEQ
DROP SEQUENCE SEQ_BILLING;
DROP SEQUENCE SEQ_SERVICE_CONTRACT;
DROP SEQUENCE SEQ_SERVICE_DELETE_CONFIRM;
DROP SEQUENCE SEQ_SERVICE_INSERT_CONFIRM;

----------------------------------------------
--DROP TABLE
DROP TABLE BILLING CASCADE CONSTRAINTS;
DROP TABLE SERVICE_CONTRACT CASCADE CONSTRAINTS;
DROP TABLE SERVICE_DELETE_CONFIRM CASCADE CONSTRAINTS;
DROP TABLE SERVICE_INSERT_CONFIRM CASCADE CONSTRAINTS;

----------------------------------------------
--CREATE SEQ
CREATE SEQUENCE SEQ_BILLING NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_CONTRACT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_DELETE_CONFIRM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SERVICE_INSERT_CONFIRM NOCACHE NOCYCLE;

----------------------------------------------
--CREATE TABLE
CREATE TABLE BILLING (
	,NO	                NUMBER	        DEFAULT SEQ_BILLING.NEXTVAL	CONSTRAINT BILLING_PK PRIMARY KEY
	,FIXED_NO	        NUMBER          CONSTRAINT BILLING_FIXED_NO_NN NOT NULL
	,PLAN_CONTRACT_NO   NUMBER          CONSTRAINT BILLING_PLAN_CONTRACT_NO_NN NOT NULL
	,BILL_MONTH	        VARCHAR2(10)	CONSTRAINT BILL_MONTH_NN NOT NULL
	,BILL_TOTAL	        NUMBER	        DEFAULT 0
    ,ETC_BIL            NUMBER          DEFAULT 0
	,PAY_YN	            CHAR(1)	        DEFAULT 'N' CONSTRAINT BILL_PAY_YN_CK 	CHECK(PAY_YN IN ('Y', 'N'))
);

CREATE TABLE SERVICE_CONTRACT (
	NO	            NUMBER	        DEFAULT SEQ_SERVICE_CONTRACT.NEXTVAL CONSTRAINT SERVICE_CONTRACT_PK PRIMARY KEY
	,FIXED_NO	    NUMBER          CONSTRAINT SERVICE_CONTRACT_FIXED_NO_NN NOT NULL
	,SERVICE_NO	    NUMBER          CONSTRAINT SERVICE_CONTRACT_SERVICE_NO_NN NOT NULL
    ,BILL_NO	    NUMBER          CONSTRAINT SERVICE_CONTRACT_BILL_NO_NN NOT NULL
	,DEL_DATE	    TIMESTAMP
	,USED_DATE	    VARCHAR2(10)	DEFAULT SYSDATE
    ,STARTED_AT	    TIMESTAMP	    DEFAULT SYSDATE
	,DISCOUNT_RATE	NUMBER	        DEFAULT 0
);

CREATE TABLE SERVICE_DELETE_CONFIRM(
    NO                      NUMBER      DEFAULT SEQ_SERVICE_DELETE_CONFIRM.NEXTVAL CONSTRAINT SERVICE_DELETE_CONFIRM_PK PRIMARY KEY
    ,EMPLOYEE_NO            NUMBER      CONSTRAINT SERVICE_DELETE_CONFIRM_EMPLOYEE_NO_NN NOT NULL 
    ,SERVICE_CONTRACT_NO    NUMBER      CONSTRAINT SERVICE_DELETE_CONFIRM_SERVICE_CONTRACT_NO_NN NOT NULL 
    ,CONFIRM_AT             TIMESTAMP
    ,CONFIRM_STATUS         CHAR(1)     CONSTRAINT SERVICE_DELETE_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);

CREATE TABLE SERVICE_INSERT_CONFIRM(
    NO                  NUMBER      DEFAULT SEQ_SERVICE_DELETE_CONFIRM.NEXTVAL CONSTRAINT SERVICE_INSERT_CONFIRM_PK PRIMARY KEY
    ,EMPLOYEE_NO        NUMBER      CONSTRAINT SERVICE_INSERT_CONFIRM_EMPLOYEE_NO_NN NOT NULL 
    ,SERVICE_NO         NUMBER      CONSTRAINT SERVICE_INSERT_CONFIRM_SERVICE_NO_NN NOT NULL 
    ,CONFIRM_AT         TIMESTAMP
    ,CONFIRM_STATUS     CHAR(1)     CONSTRAINT SERVICE_INSERT_CONFIRM__STATUS_CHK CHECK(CONFIRM_STATUS IN ('N', 'Y', 'A'))
);

----------------------------------------------
--FK ALTER
ALTER TABLE BILLING 
ADD (
CONSTRAINT BILLING_FIXED_NO_FK             FOREIGN KEY (FIXED_NO)         REFERENCES FIXED_INFO (NO)
, CONSTRAINT BILLING_PLAN_CONTRACT_NO_FK    FOREIGN KEY (PLAN_CONTRACT_NO)  REFERENCES SERVICE_CONTRACT (NO)
);

ALTER TABLE SERVICE_CONTRACT
ADD (
CONSTRAINT SERVICE_CONTRACT_FIXED_NO_FK     FOREIGN KEY (FIXED_NO)     REFERENCES FIXED_INFO (NO)
, CONSTRAINT SERVICE_CONTRACT_SERVICE_NO_FK  FOREIGN KEY (SERVICE_NO)    REFERENCES ADD_SERVICE (NO)
, CONSTRAINT SERVICE_CONTRACT_BILL_NO_FK     FOREIGN KEY (BILL_NO)       REFERENCES BILLING (NO)
);

ALTER TABLE SERVICE_DELETE_CONFIRM
ADD 
(
CONSTRAINT SERVICE_DELETE_CONFIRM_EMPLOYEE_NO_FK           FOREIGN KEY (EMPLOYEE_NO)           REFERENCES EMPLOYEE(NO)
, CONSTRAINT SERVICE_DELETE_CONFIRM_SERVICE_CONTRACT_NO_FK FOREIGN KEY (SERVICE_CONTRACT_NO)   REFERENCES SERVICE_CONTRACT(NO)
);

ALTER TABLE SERVICE_INSERT_CONFIRM
ADD 
(
CONSTRAINT SERVICE_INSERT_CONFIRM_EMPLOYEE_NO_FK   FOREIGN KEY (EMPLOYEE_NO)   REFERENCES EMPLOYEE(NO)
, CONSTRAINT SERVICE_INSERT_CONFIRM_SERVICE_NO_FK  FOREIGN KEY (SERVICE_NO)    REFERENCES ADD_SERVICE(NO)
);


